### ISSUE TITLE
Vertical equivalents are not available for fence gates, springy wooden door on tracks

### ISSUE THREAD

**Issue by bpskotch** [jasonrohrer/OneLifeData7#1008]
Since you're back in the dev game, I feel its worth bringing up something that's bugged me for a while. Two issues but very similar in nature:

1. There are fence gates for horizontally laid fences, but not for vertical.
2. You can place a springy wooden door on a straight vertical rail track (thus forming a horizontal aligned door), but there is no equivalent for a horizontal rail (thus forming a vertical door)

**Comment by jasonrohrer** [comment]
I think it was a matter of them just being really hard to see, and also maybe some weird visual overlaps that I couldn't solve.

In the case of animal fences (thick fences), the gate opens vertically by swinging up.  With the way it overlaps stuff visually, it was very hard to make a N/S animal fence gate that you could actually see clearly.

Same for property gates... they were so thin that they were hard to click on and mouse over.  Since they are key to ownership, I wanted it to be crystal clear where the gate was.

Finally, for the springy doors on tracks.... I'm pretty sure there was a draw-order issue that had no solution there, as the cart moves through that area, since the cart needs to overlap stuff as it slides into that space.  In the N/S version, it worked okay, because after the door is open, the cart doesn't overlap with anything but the track.  But in the E/W version, the cart also had to overlap with the open door.

This has something to do with how moving things work, where they "move onto" something before transforming it.

Anyway, the answer is that there's a pretty good reason for the omission in each of these cases.
