### ISSUE TITLE
recipes for convenience

### ISSUE THREAD

**Issue by GitHubBoi415** [jasonrohrer/OneLifeData7#1014]
working on farms can be very tedious, so I was thinking there could be some new recipes to make it less tedious.

For example, what if using an empty basket on a ripe grape plant collected all the grapes into the basket, without having to manually pick all the grapes one by one?

Or maybe using a sharp stone on a pile of corn ears instantly turns that pile into a pile of shucked corn?

Or maybe using a bowl on a berry bush collects all the berries on the bush that can fit into the bowl?

**Comment by jasonrohrer** [comment]
This may sound strange.... but the tedium is intentional.  One of the core aesthetics of the game is the fiddly nature of crafting and farming in real life.

If you ever pick berries in real life, you pretty much do it one berry at a time, plunk plunk plunk into a bowl.

I have definitely considered "automating" things like berry picking, but decided against it.

Green beans are the one item that work differently, and there's some good reason for that, but I don't recall what it is.  I think it has to do with the way they have to dry on the plant, and thus they have an all-or-nothing harvest condition.
