### ISSUE TITLE
Need means to remove ancient walls.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1016]
![Screenshot_2023-06-09_224848-1](https://github.com/jasonrohrer/OneLifeData7/assets/53706597/2de97454-da00-4de3-beb9-e810c5420708)

Again same issue with the gates thing. We are having to use other exploits to stop these and it's beyond frustrating. Please make sure to look into the gate fixes and ancient walls.

Next is gonna be stable tower bases. You cannot have things that cannot be deconstructed or this is what happens.

**Comment by jasonrohrer** [comment]
Pretty crazy... how did they get that much food in there?

**Comment by Tarr-OHOL** [comment]
A whole lot of farming of corn lol. 32 cobs per mine cart, 28 carts. Yeesh, they grew a ridiculous amount of the stuff to eat corn. As you can see the only way to actually get in there was through players flying a plane into the wall. Wasn't a part of this specific towers destruction so I can't give you the details on if or why they didn't just curse the players inside and stop them from being reborn. 

Actually I think exiled is the dude with a bunch of accounts and because curse tokens require 20 minutes to refresh the dude would be able to cycle accounts. Ancient stone walls and stable bell tower bases are some of the last items in my immediate memory that cannot be deconstructed. As long as this exists people will have to use planes to stop attempts like this which thematically doesn't make sense.

**Comment by jasonrohrer** [comment]
Ancient walls are supposed to crop up in abandoned areas, mainly.... so you discover them when walking through the woods and say "wow".

They're not meant to have people use them intentionally for structures.

But I don't think there's any support in-engine for transitions that happen simply when people are nearby... i.e., so that just walking around near them would prevent them.

One thing that's kinda wild... what if the bones/grave was a tapout trigger that cleared nearby ancient stone walls and made them fresh again?  So that anyone living/dying nearby would prevent them from being ancient walls (the moss "rubs off" due to human activity nearby).

The problem with this is that there'd be some max radius for the tapout, and peeps would just figure that out and build walls big enough that they could die in the middle without tapping them out.

I guess the same is true for any "human activity" effect on them.... make them big enough and far away enough (big enough arena of walls) and they'd be out of range.

**Comment by jasonrohrer** [comment]
Probably just going to let you destroy them at will....  one of OHOL's sacred cows has finally fallen.

**Comment by Tarr-OHOL** [comment]
Yeah I think it's a real shame that stuff like this has to happen because ancient walls are nice to show a town has actually stuck around for a while. Maybe ancient walls just have to go ancient in a much longer span of time? Maybe instead of ten hours it takes a week? It would still likely be a problem because then instead of an apocalypse attempt going off every day it would take a week to set this up? A month? I hate that bad actors are abusing something this way but we don't want the game to have to resort to other exploits to stop the unstoppable. 

We would be back to square one with unbreakable wall forts

**Comment by jasonrohrer** [comment]
Well, for now, I'm just making them pickaxable like normal stone walls.

If a village cares for their walls for 10 hours, they will become ancient.  But they still need to protect them after that.
