### ISSUE TITLE
Means to deconstruct layers of bell tower bases

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1019]
Note: misremembered a bit in here. After 10 hours these become stable and unremovable like ancient walls. 

Suggestion is that once stable to allow elder removal notes to allow removal of blocks as needed. Sucks to have to have everything unconstructable but bad actors will be doing this eventually.

**Comment by Tarr-OHOL** [comment]
To note: This is the last item that a player can construct that cannot be removed once settled. With the apocalypse attempts what is occurring is players taking over old abandoned towns to set these towers up which no one visits because who is gonna search every single town for baby towers? 

Since the warning trigger happens at 12 hours by the time you know an apocalypse has been started these will be stable and now unremovable.  I still suggest some sort of method to pull off the tower pieces (which sucks because making a bell tower requires a lot of time) I'm not 100% certain if just allowing something simple like a shovel to remove pieces or a notice would be proper. With a notice you make it so it's not done without a fight BUT you cannot stop someone behind an impenetrable wall. A shovel makes it so you just dig them up and easily remove hiding behind them but makes it incredibly easy to grief bell towers.

**Comment by jasonrohrer** [comment]
Yeah, easy fix here is like the gates:

You can't build multiple tower bases near each other (due to tapout triggers)

Obviously, if you were really building a bell tower, you wouldn't want multiple tower bases right next to each other.

This will prevent them from being used as permanent walls.

**Comment by Tarr-OHOL** [comment]
What's the tap out range on gates and bell tower bases? If it's <2 they meta will be gate, bell tower base, gate, etc. Since walls are being destroyed there shouldn't be a third unremovable item left that I can think of.

**Comment by jasonrohrer** [comment]
Well, this is actually more complicated, b/c of the multiple levels of the tower.

The bases can't just tapout each other, b/c someone could grow a tower first, and then build a new tower base next to it.

And you don't want small tower bases tapping out whole towers (would allow griefer to cheaply stop a legit bell tower effort)... so that means that the big ones should tap out the small ones... but then someone would just finish a big one and *then* build a small one next to it.

The other hard part is what happens during tapout.  You'd like to get the stone blocks back, but there are a variable number of them as the tower grows.

**Comment by jasonrohrer** [comment]
Good thought on the alternating of things that don't tap eachother out... hmm
