### ISSUE TITLE
springy wooden door can only be added to north south track

### ISSUE THREAD

**Issue by plasticbrrr** [jasonrohrer/OneLifeData7#1040]
would be nice if east west track worked too

<img width="296" alt="Snímek obrazovky 2023-07-14 221003" src="https://github.com/jasonrohrer/OneLifeData7/assets/139589068/a90b9b1a-6ecc-49c5-8824-d2d49bcd5019">

**Comment by cordy-123** [comment]
Already looked at by Mr. Rohrer here last month https://github.com/jasonrohrer/OneLifeData7/issues/1008

"Finally, for the springy doors on tracks.... I'm pretty sure there was a draw-order issue that had no solution there, as the cart moves through that area, since the cart needs to overlap stuff as it slides into that space. In the N/S version, it worked okay, because after the door is open, the cart doesn't overlap with anything but the track. But in the E/W version, the cart also had to overlap with the open door.

This has something to do with how moving things work, where they "move onto" something before transforming it.

Anyway, the answer is that there's a pretty good reason for the omission in each of these cases."

**Comment by plasticbrrr** [comment]
i tried to search if there had been a similar topic but must've missed, still trying to find my way around here lol. thank you for the replies!
