### ISSUE TITLE
combining partial filled bowls

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLifeData7#1045]
another one I'm forwarding from the reddit https://www.reddit.com/r/OneLifeSuggestions/comments/152i82v/combining_storage_content/?ref=share&ref_source=link

they seem to want the ability to take partially filled bowls of things and combine them. It'd be an interesting feature. Most people underestimate how important having spare bowls is for towns.

**Comment by jasonrohrer** [comment]
Whoops... I was wrong about this.

Popcorn and Green Beans are both the things that you can't either add or remove items from the bowl.  There is no "Green Bean" item that you can just hold in your hand.  You pick them with the bowl (all together... which does kinda violate my "it should feel like real life" requirement).  And then after that, you never hold a single bean in your hand.

This is also inconsistent with the dried beans, which you do pick one by one.

I will change the green beans so that you pick them one by one.

Note that green beans do not "dry out" after being picked in real life.  If you want actual bean seeds, you need to let them mature and dry on the plant.  So that will remain in OHOL.

**Comment by jasonrohrer** [comment]
Welp... the green bean plant sprites are unfortunately baked together as one sprite (with no separate beans).  I did that for efficiency (so all the leaves don't have to be separate sprites, and the leaves can be in front of some of the beans).

I'd have to go back and re-build it from the parts, which would take a long time, and never look quite the same as what's currently in the game.  I don't want to do that.

So I'll just make it so that you can remove a single green bean from a bowl, which will allow you to transfer them between bowls.
