### ISSUE TITLE
cant add soil to hardened rows in the arctic

### ISSUE THREAD

**Issue by plasticbrrr** [jasonrohrer/OneLifeData7#1046]
encountered a farm that was partly in the snow biome. found out it is possible to make a soil row in the snow by using a hoe on a basketful of soil. however, once the plant is harvested and leaves behind the hardened row, it's not possible to reapply soil and the only option is to remove the hardened rows with a shovel and make brand new rows. don't know if it's intentional or an oversight.

**Comment by Wotte** [comment]
![2023-07-22 07_30_55-SDL_app](https://github.com/jasonrohrer/OneLifeData7/assets/1755160/01a4d7d4-e638-49a8-88d5-20eded66e9a3)
I try it too, even as a ginger it's not working and even with just one tick of soil it's not working, maybe it's because it's too hard to grow things in very cold place in real life, witch make sense but in that case in desert you should not be able to harvest too ( i try on desert it work well ).
That true that is weird to see so fragile plants like cucumber or tomato grow in desert or arctic biome, to fit with reality you should be able to harvest only the correct plants, like the glasswort witch is only grow-able on desert.
![2023-07-22 08_53_53-SDL_app](https://github.com/jasonrohrer/OneLifeData7/assets/1755160/c3bea04b-35fc-4b9e-b3b0-71ecdee1a40b)

**Comment by TwistedHBG** [comment]
This is intended, farming in snow biomes used to be completely impossible but then triple soil got added as an option

**Comment by MrMendeleev2** [comment]
1136-Shallow-Tilled-Row-groundOnly-biomeBlock4
![image](https://github.com/jasonrohrer/OneLifeData7/assets/91346213/b2336746-59fd-4ce6-9cd2-557cecc80189)
"-biomeBlock4" means any transition creating this item is blocked in arctic. So 

> This is intended, farming in snow biomes used to be completely impossible but then triple soil got added as an option

therefore using triple soil is an exploit. 

> That true that is weird to see so fragile plants like cucumber or tomato grow in desert or arctic biome, to fit with reality you should be able to harvest only the correct plants, like the glasswort witch is only grow-able on desert.

desert works cause you have to harvest glasswort there. 3703-Dry-Planted-Glasswort-Cutting-Desert-Only-biomeReq5
"-biomeReq5" means desert only, so you have to be able to make rows there, but Jason could biome-restrict some plants, like he did with glasswort but reversed, so they can only be planted outside of harsh biomes this sounds reasonable.

**Comment by plasticbrrr** [comment]
> therefore using triple soil is an exploit.

well, 'exploit'. it eats up so much soil i cant imagine people abusing it much (except mabye for berry bushes and trees?) + i think you should be able to plant pine trees in the snow, as they grow there naturally, so soil _should_ be usable.

thank you for the replies. should i close the topic or leave open for the plant restriction idea?

**Comment by Wotte** [comment]
You should probably leave it open for the plant restriction idea ^^ Let's wait Jason answer.

**Comment by TwistedHBG** [comment]
> 1136-Shallow-Tilled-Row-groundOnly-biomeBlock4 ![image](https://user-images.githubusercontent.com/91346213/255656347-b2336746-59fd-4ce6-9cd2-557cecc80189.png) "-biomeBlock4" means any transition creating this item is blocked in arctic. So
> 
> > This is intended, farming in snow biomes used to be completely impossible but then triple soil got added as an option
> 
> therefore using triple soil is an exploit.
> 


No, it's intended - https://github.com/jasonrohrer/OneLifeData7/commit/855a516749b9ba7a99a5722b54b085dcb6473908

**Comment by jasonrohrer** [comment]
Yes, this is intentional.

It's also not possible to make a deep-tilled row using just the two-soil pile.  But a three-soil pile can be used to make a row anywhere, even in the arctic.  Farming is supposed to be much harder in the arctic.
