### ISSUE TITLE
banana bread

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLifeData7#1048]
this person just really likes banana bread

https://www.reddit.com/r/onehouronelife/comments/155apor/what_is_the_best_openings_statement_for_a_baby/jswync6/

I think I've seen them mention this one on the discord too.

- Banana mash in bowl 
- add to crock 
- add sugar 
- add egg 
- add flour 
- Mix with stomper 
- Click crock with plate Bake in oven 

Honestly sounds like a terrible thing to get a family craving for, but could live with it.

(They where so close to making that a markdown list that would have worked in the reddit comment too.)

**Comment by TwistedHBG** [comment]
The issues should be used for reporting bugs, problems, inconsistencies, and actual issues rather than suggesting new content such as brand new food recipes otherwise there will be no end to it.

**Comment by squishysquid** [comment]
eh it's a ticket queue commonly you have a different tagging system for feature/bugs But I don't think anything that complex is going on, it is basically just jason.

**Comment by jasonrohrer** [comment]
Yeah, I do want to keep this list for inconsistencies, bugs, glitches, etc.

For example, being able to cultivate willow and bald cypress trees, while that might be seen as a new content suggestion, was actually a consistency hole in the existing content (since you can cultivate all the other types of trees, it's weird that there's no way to cultivate these two swamp trees).
