### ISSUE TITLE
Suggestion RE: Stone wall storage

### ISSUE THREAD

**Issue by oholsuggestions** [jasonrohrer/OneLifeData7#1059]
Problem: We can currently only place boxes on the wooden walls. This limits the kind of wall to use when you need storage options. 

Solution: Use wrought iron to make a variety of storage options i.e.

Wrought iron brackets, allows you to store two boxes or mechanism together.
Wrought iron hooks, allows you to store 4 tools or a tapestry.
![Wrought iron brackets+ hooks](https://github.com/jasonrohrer/OneLifeData7/assets/97406873/4b7d5943-b0f8-4e56-a652-b5e62a908ce8)

**Comment by Forman9** [comment]
Agreed stone walls should at least be able to support one box

Granted adobe is more expensive, hence the additional functionality
**NOTE: a middle ground here would be adding a new wall 'plastered stone'**

Unfortunately, this means that buildings always look exactly the same (when built efficiently) with adobe east/west walls and stone north south walls which makes for pretty boring aesthetics 

This is also an issue for survivability because sometimes there is more stone than say, clay, which makes stone a better option.
Towns evolving in response to natural resource distribution is also more realistic.

**Comment by jasonrohrer** [comment]
This was fixed in 6f1f981f2a6f06448f260929102e55ac258b92b7
