### ISSUE TITLE
Milkweed Should Grow Back (Like Mushrooms/rabbits)

### ISSUE THREAD

**Issue by Forman9** [jasonrohrer/OneLifeData7#1078]
I mentioned already that milkweed water cost is far to expensive.

I think this is a main reason why many Eve towns die.

A simple solution would be that milkweed should grow back like mushrooms/rabbits.

Simple use of a shovel to destroy the stump.

**Comment by TwistedHBG** [comment]
This is not why Eve towns die, Eve towns don't need to even grow milkweed because it's plentiful in the wilds around them

**Comment by TwistedHBG** [comment]
Also rabbits don't really regenerate without player input. Sure, they do respawn, but you don't get anything out of them unless you invest resources (bait)

**Comment by Forman9** [comment]
> This is not why Eve towns die, Eve towns don't need to even grow milkweed because it's plentiful in the wilds around them

In the last couple months I played, I'd say eves have an 80-90% death rate.
The towns ultimately die because they cannot produce food fast enough.

This is ultimately because they cannot move through the eve tech/steps fast enough.

A major contributor to this fact is players having to run around collecting milkweed further and further from their home position without the aid of backpacks, horses or carts.

Noobs also often waste milkweed on things like thread for clothes or ropes on primitive hoes.

This is also assuming there IS actually enough milkweed (and many places there is not).
One major reason there may not be is because the area has already been cleared out and basically never grows back.

There are also locations where there simply is not enough milkweed nearby and a noob players seldom pick good positions for new towns.

Besides all of these facts, I have eved enough times to know there is simply never enough milkweed.

As a veteran player, I can survive, sure, but many of the players born into noob camps die while I am way off collecting milkweed for critical equipment.

One of the most important eve strategies I employ is gathering as much rope as possible before actually choosing a base position.

So no, there is definitely NOT enough milkweed.
And having to consume 4 bowls of water (which is limited, and so is oil) is also far too expensive for one rope.

The honest truth is that the only reason towns survive at all is by relying on highly experienced players and/or by stealing things from old bases (that were built/supported by experienced players)

**Comment by TwistedHBG** [comment]
Do you have the actual log data for this or are you just making up numbers?

**Comment by wiogit** [comment]
> I think this is a main reason why many Eve towns die.

In the past, if you picked milkweed in the wild while it was seeding, it would regrow. This was taken out on purpose so that milkweed would be more scarce. As I understood it, milkweed was altered to be a bigger challenge. So if it is killing Eve towns, it's a feature not a bug. That's why this argument won't go anywhere. Jason wants the average Eve town to fail.

> This is not why Eve towns die, Eve towns don't need to even grow milkweed because it's plentiful in the wilds around them

I don't think we can have an honest conversation about this, because every village seems to be airdropped vital resources from trucks. A village will have a bunch of clothes and yet no loom or even a sheep pen in some cases. I was in a village that had 4 trucks, but the well had not gotten to the engine stage yet.

Towns won't plant milkweed because they can just get a bunch of milkweed based items dumped on them by a neighboring civilization. This doesn't apply to food because people constantly need to consume it, so it must be grown to keep up with consumption.

Milkweed absolutely was a bottleneck in the past, and I'm pretty sure it was intended to be so.
