### ISSUE TITLE
Domestic Turkey

### ISSUE THREAD

**Issue by ShamWish** [jasonrohrer/OneLifeData7#1081]
All other animals are able to be domesticated except bears and turkeys. 
As towns get larger, turkeys get hunted out, and you have to go further and further out to find one. Being able to breed them would eliminate this problem and make the game more consistent. 
Credit to Rukhran on discord

**Comment by jasonrohrer** [comment]
Yeah, this is a reasonable suggestion.

However, I'm going to keep it the way that it is, for now, because that makes the turkey a special wild food, needed for the feasting table, which is like a "first thanksgiving" kinda thing.  Coming back to town with a turkey, to complete the feast, is a major accomplishment.
