### ISSUE TITLE
The Fishing Problem

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLifeData7#1083]
Right now, fishing is one of the worst cravings to have. A cursory glance at the public data reveals that on many days, even the feast plate is a more popular food item. This is due to a combination of several frustrating aspects:
1. Fishing requires worms, and worms are awful to acquire. One soil pit provides three, but they do not come back and there is no way to farm them. Getting more requires travelling far from town, moving all the soil out of a fresh deposit, collecting the three worms, and searching for the next soil deposit. For big cities, this means travelling very far away since the nearby soil pits have already been exhausted. Some improvements to the worm collection process are warranted:
   - Worm pits could provide six worms (a full pile/bowl) instead of three.
   - Worms could return to the mushroom pit after some time.
   - There could be a larger vessel to transport worms. Maybe a bucket of worms (which holds ten bowls of worms)?
   - Most importantly, though, worms could be farmable in some manner. We already have compost, so this doesn't seem like a huge stretch. Maybe allow adding a worm to a composting pile, which results in making extra worms later? Other ideas are possible here.
2. Fishing takes a long time. At five seconds per cast, and with only a 15% chance to get a fish per cast, it takes 19 casts over 95 seconds to have a 95% chance to catch a single fish. This is very long time (over 1.5 years) in OHOL terms. It is strange how most other activities in the game happen instantly, whereas fishing does not, given how one second basically translates to nearly a week of our character's life. Either improving the odds or reducing the time per cast would be a good improvement.
   - Many of the casts result in the worm coming back up, so just reducing this possibility and increasing the odds for the other possibilities would have the same effect as reducing the fishing time per cast.
   - Catching shrimp has a similar problem, but it is not nearly as problematic since shrimp aren't affected by points 1, 3, and 4.
3. The chance of catching a fish per worm used is poor. It is only 37.5% per worm. A slightly larger probability results in the worm being lost (and sometimes the hook, too), and half of that probability results in a boot coming up. But really, although it is amusing to fish up a boot, there should not be half as many boots as fish in the sea. This event should be far rarer. It would be nice to double these odds of catching a fish to 75% per worm used.
   - Maybe add a pile of old boots, too.
4. A single fish provides only a single meal for one person. Given all the effort required to produce a single fish, trying to fish for your family would surely result in them starving. Other cooked animals provide multiple uses, such as duck (2 uses) or turkey (6 + 2 uses). Even shrimp and ice cream, which are also specialty items, provide 4 uses each. Arctic char are no small fish, either.

**Comment by DiscardedSlinky** [comment]
We definitely need a new way to get worms at the very least. The current way is just ridiculous.

**Comment by jasonrohrer** [comment]
Ah, the hard life of a grizzled fisherman!

The reason the casting system is random, instead of instant, like many other things, is that it was introduced as a test case for the new random transition system (way back when).  I think that the gambling devices (dice, cards) were introduced at the same time.  Yes, indeed, the Games of Chance update:

https://onehouronelife.com/forums/viewtopic.php?id=4363

It also is a nice thematic match for fishing, which is very random.  Some days you go out (in real life) and get nothing.  Not a single fish.

As far as feeding the family goes, well, fish aren't that big.  You probably need to come back with a whole cart full.

Now, I see that the worm situation is dire, and I will add some simple worm farming thing with compost.

Seems like maybe a bucket of worms is in order too.  I will look into it.
