### ISSUE TITLE
Stuck Highway Paver

### ISSUE THREAD

**Issue by Hopie-OHOL** [jasonrohrer/OneLifeData7#1084]
If a highway paver runs into bear cave or another immovable object, there is no way to redirect it. It is stuck. The only option is to use a hammer to stop the paver, move it by hand, and replenish all the resources it needs to run from scratch. So get a second full crude tank, a second bucket of yellow paint, and a second bucket of gravel which means a second round of expensive trade with at least two families. In practice this means most highway workers just get frustrated and give up if the paver gets stuck. It would be good to have a way to back the paver up, reset it, make it turn when stuck, etc. In real life, construction workers have the option to manually turn pavers, reverse, stop in place, etc.

**Comment by oholseven** [comment]
Or just give us dynamite so we can blow up empty bear caves as needed.

**Comment by jasonrohrer** [comment]
Yes, this is a good idea.... though I don't want to undercut people planning their roads with the little arrow direction things.

I mean, if you could just click the paver to turn it whenever...

Maybe it needs to go into a stuck state first, and then you can turn it?

**Comment by oholseven** [comment]
I have two stuck pavers on a small server, due to a griefer sending them purposely into bear caves.  Waiting to see if there is a fix on this, instead of tearing the pavers apart and reloading them.  I do enjoy the little curves and turns we can make with directional markers when paving, and normally you wouldn't loose a paver without being present or marking the routes out ahead of caves.  There needs to be some responsibility on the player using the paver, keeping ahead of it to mark the way, so usually they aren't sent straight into bear caves.  Unattended pavers get hijacked though.  I would rather be able to remove the cave only if a paver is stuck on it, which would require more work - ie, removing the bear first, then making something like dynamite to destroy the cave, but normally you would be able to route around caves ahead of time, with directional markers, to prevent having to remove the cave.

**Comment by skps2010** [comment]
Maybe add a way to make pavers move "backward" for only one block, so you can't use this method to make new roads.
Like right clicking a paver while riding a horse, because horses are stronger than humans, and the wheels on the paver allows it to move backward.

For example, if you have a "Running Paver North - was W", and rigit click it while riding a hourse, the paver will move east for one block and become "Running Paver West"

**Comment by jasonrohrer** [comment]
Yeah, as I'm thinking about this, I'm worried that it will undercut planning of roads, which I like.

Like if you could just let it get stuck and then turn it at will later, people would make the entire road that way.  Why would they bother planning it out, clearing the way, putting the directional markers in, etc?

Remember, if planned properly, this already offers something like infinite free roads from one batch of resources.  But you do have to plan properly.

I will think about some version of this that has less cost than losing everything, though.

Like what if you could stop the paver by hitting it (stuck or otherwise), and it just burned the fuel, but kept the other resources?

But there's another question lurking... what would EVER cause the resources to get consumed?

Right now, they get consumed whenever the paver gets to the "end" of the desired road, and someone wants to pick it up to use the paver elsewhere.

If players could stop the paver and reclaim the resources, they would never get consumed.

While I like the idea of an infinitely-long road for one batch of resources, if planned properly, I don't like the idea of infinite separate roads from one batch of resources.

But again, I don't want to completely undercut road planning here.

Thus, I don't think there's a good solution.

(Well, there is a solution:  plan your roads well, and don't let griefers access your pavers).
