### ISSUE TITLE
Crock pots containability on tables

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#1088]
Ages ago when Sauerkraut and Stew was added people asked why it was not containable, and (correct me if I'm wrong) you said that when you make Sauerkraut at home you keep it on the table until it is eaten and the pot is empty.

Well, we have tables now, and pots of Sauerkraut cannot be put on it for the family to enjoy.

I'm proposing allowing the crock pot items, Open Fermented Sauerkraut (ID 1241), Open Fermented Pickle Crock (ID 4303), Three Sisters Stew (ID 1249), Pumpkin Custard (3390), and Turkey Broth (ID 2197), being pickupable and placeable on tables, so we can all share those foods together in the kitchen.

**Comment by jasonrohrer** [comment]
Yes, this is a good idea.

I'll have to do some thinking about it, though, because a 5-gallon crock is extremely heavy once its filled up, and it really can't be moved much.

At home, we actually "stomp" the cabbage with the crock on the floor (with a big wooden stomper), and then after it's full, we carefully lift it up onto the counter to ferment for a few weeks.  But... it takes two people to lift it, and we do a lot of groaning when we do this (and my wife can't do it... my oldest son and I are the ones who help lift it).

So it seems like the crock would go on the table, and then you could do the ingredients up there.  But it would kinda be stuck up there during the process, until the crock was emptied (just like it currently gets stuck on the ground.

I don't have time to squeeze this in this week, so maybe we'll get a chance to discuss more here.

**Comment by jasonrohrer** [comment]
There is a wrinkle here, and that's that the engine doesn't support objects that are both permanent AND contained.

So you can't make objects that are stuck in a container.

Thus, you can't start making Kraut on the table, reach a state where it doesn't make sense to be able to pick it up, and then have it remain stuck on the table until that part is done.  If it's in a container, the engine always lets you pick it up.

For the ones that are made on the fire, I'm going to leave them as-is, b/c they are big and heavy and hot.  You can bottle the broth to use in the kitchen.

But I will allow you to pick up the finished kraut and put it on the table.  I suppose there are several stages that should also be moveable (like while fermenting), but they will be heavy and slow to move.

It is stomped on the ground, however... you have better leverage that way!

**Comment by jasonrohrer** [comment]
I'll do something with the pickle crock also.
