### ISSUE TITLE
Higher yield slower worms?

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1095]
First off I appreciate the worm breeding finally being added to the game. I ended up spending a life breeding worms and ended up positive about 84 worms (3 - 1) which means I ended up making 42 compost piles which means by myself I ended up with a byproduct of 882 soil for the town.  

This is obviously kind of excessive for one person to be producing this much soil. Yes, some of this is going to go back into having to produce the berries, carrots, and (maybe wheat).

Could we potentially get a slower version that doesn't produce soil as a byproduct? Or maybe the recipe is faster but keeps a higher cost? I like in the current composting system that worms are a bonus if you care to do it but when specifically going out of your way to do this it floods an area of the map with composted soil. 

Maybe box + berry carrot mush = incomplete breeding box
Breeding box + straw = dry breeding box
Dry breeding box + dung = Prepared breeding box 
Prepared breeding box + worm = Complete breeding box 
Completed breeding box + 10 minutes = 5 worms (or whatever number)
Once you take the last worms out it can revert to the incomplete breeding box thus requiring more poop and straw. 

This would allow for dung to be used more consistently because I wasn't able to actually use all the town poop in my worm adventures lol.

**Comment by Tarr-OHOL** [comment]
Actually to note apparently I can't count and a bucket of worms is 30 total worms, I thought I read 3 instead of five uses. 

This means you need 10 compost piles per bucket (if not saving worms for more breeding) or 15 compost piles. That's a lot of soil for a single bucket.

**Comment by TheMingo888** [comment]
I agree that this is a problem. The current method of farming worms leads to a ton of excess soil if you actually try to produce enough for a fishing expedition. The profit from one compost pile (2 worms) isn't even enough for a single fish. And all the excess soil poses a problem for towns, since it can't be easily removed.

The method Tarr suggested for worm breeding sounds good, but there are probably also simpler changes that could alleviate the issue if you don't want to spend too much time on it:
- Allow reusing the same compost pile while breeding worms, instead of having to make a new pile each time.
- Instead of using one worm in a pile to produce three, use one full bowl of worms to produce three full bowls of worms. This keeps the breeding ratio the same (1 worms breeds into 3), but allows bulk production. I wouldn't mind if the amount of soil produced from one pile was reduced in such a scenario.

**Comment by oholseven** [comment]
Just give us more worms.

**Comment by wiogit** [comment]
When playing single player, if you worm every compost then you'll have more worms than you'd ever need.

**Comment by oholseven** [comment]
Problem is having to make too much compost to farm two worms.  To catch ten fish, you would fill your farm with compost, since most worms are wasted when fishing.  And now I have 20 compost piles an a tiny one-player farm.  More worms per batch would help.

**Comment by jasonrohrer** [comment]
Yes, I see the problem here!

**Comment by jasonrohrer** [comment]
Also, worms should speed up composting, like they do in real life.  I can't believe I missed this.

**Comment by jasonrohrer** [comment]
Seems like the wormy soil could keep making worms slowly over time...  Like as long as there were some worms left, it would slowly refill with worms.
