### ISSUE TITLE
Track cart change makes indestructible walls

### ISSUE THREAD

**Issue by Hopie-OHOL** [jasonrohrer/OneLifeData7#1116]
Hi Jason,

The new change that makes track carts impassible will also make indestructible walls possible. If someone wants to wall off an area (the town’s well, an apoc tower, an iron mine, etc.) they could make a series of 1x2 tracks full of carts around the area. So a west track end with east track end on the sides and north with south on the top and bottom. The carts couldn’t be derailed without removing the track, the track couldn’t be removed without removing the cart, and the carts can’t be walked through. If people used this on the wells they could cripple or kill a town with only a few springs, blades, and butt logs.
![7E1C7707-7F3A-434C-855D-EF2E15EFE124](https://github.com/jasonrohrer/OneLifeData7/assets/145514068/0fa52bb2-f0ef-432b-ae1d-d722a9630d5e)

**Comment by jasonrohrer** [comment]
Nice catch!

Is the only way to deconstruct a cart to derail it?  I will fix that?

**Comment by jasonrohrer** [comment]
I'm pretty sure that this fix is sufficient:

https://github.com/jasonrohrer/OneLifeData7/commit/d18aaebfef8f008e95e7ec1e1985cd3245ee92d0

Carts in motion always end up at track ends.  If two carts are butted together in the middle of a track, they can be reversed by clicking on them.

If the track does not end with a track end, but with some other blocking object, the cart will stop there and not be removable.  However, *that* other blocking object can be removed, and then the cart will go off the end and derail.

I was also worried about Celtic Knot style track arrangements, where carts block the motion of other carts, making them all immovable.  But I don't think this is possible, since cart motion can always be reversed with a click.

We'll see if something crops up that I'm not foreseeing here.
