### ISSUE TITLE
Cannot use Axe as a weapon

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLifeData7#1122]
In real life an Axe can be used as a deadly weapon so why not here?

Having more tools to use as weapons makes it also easier for a majority to fend of of an minority since it provides a higher probability of having enough weapons in case of an attack.

Additional Stone Hatchet / Stone Hoe could be also used as weapons but should maybe have a lower hit chance like 20% or something or need more hits.

General it would be interesting to use one of the quite empty servers as a combat allowed server. This would give players with different playstyles more options and create more stories and allow to experiment with different combat changes. Donkey Town people could be forwarded to this server by default.

**Comment by Shadie116** [comment]
So can a chisel and a hammer, also Jason add multitools

**Comment by Shadie116** [comment]
Jason add flint knives so you can cut turkey at a primitive age. I know dam well my ancestors were rockin those flint and obsidian knives back then, don't even lie. And don't you dare forget the flint spears

**Comment by jasonrohrer** [comment]
Yeah, I think with the sword, knife, and bow, there are enough weapons around in the game.  It's not hard to make any of these things.  While there need to be a way to kill people in the game, combat has never been the focus of this game.  In fact, with the way things are implemented between client and server (to support a hundred+ simultaneous players on an infinite, player-generated map that has no forced wipes), combat is pretty darn janky.

People have also asked about guns, rockets, and other advanced weapons.  It's just not the focus of the game.

Also, where each "soldier" is a real person (instead of an NPC minion), and death is permanent (there's no respawn, at least not back into the same battle), war is just not interesting game play.  In an RTS, where none of these things are the case, ware is interesting gameplay indeed.
