### ISSUE TITLE
Usability issue: Dropping or storing an adze requires work-around mechanics

### ISSUE THREAD

**Issue by bluemist64** [jasonrohrer/OneLifeData7#1125]
Floors and storage objects are unintentionally deconstructed when the player tries to drop or store an adze using the standard controls. 

Currently, players are using the following work-around:

1. Ensure another item is located where you want to place the adze
2. Swap the adze in your hand with the item in the target tile

**Comment by NotSoShady116** [comment]
I don't got nothing to say about this, no joke this time

**Comment by Shadie116** [comment]
Yup still nothing

**Comment by jasonrohrer** [comment]
Yeah, there are some funny edge cases like this.  I will take a look

**Comment by jasonrohrer** [comment]
Hmm.... there are only two things that can be used on a stone floor:
--Mining Pick
--Bear Skin

There are only two things that can be used on a wood or snow floor:
--Adze
--Bear Skin

As a result, it's impossible to set these items down on the floor.


This is a limitation of the mouse UI.

--Left mouse button walks someplace, but only if you click on the ground (or a floor, which covers the ground).
--Left mouse button on an object carries out an action on the object (transforms it, picks it up, inserts).
--Right mouse button on bare ground (or usually floor) sets something down or swaps.
--Right mouse button on floor with a tool that works on the floor transforms the floor.

There's not a better place for these floor-specific actions.  They are a special case, because you're constantly clicking on a floor when you just want to walk there, so it has to be right mouse button.

I could make some other special command, but I think that would just be more confusing.... and it's only for 6 cases.

People do figure out their work-arounds, and it's not that hard to re-build the floor if it gets messed up by accident.
