### ISSUE TITLE
Despawn time for defaced bones?

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#1130]
So this is a multiple level issue: 

One - Sids bones can be defaced which turns them to normal bones. This means someone with a pencil can go around and turn baby bones into much longer lasting bones. No one is naturally going to do this to sids bones unless they're trying to speedrun a graveyard or make an annoyance. 

Two there's zero despawn time like the other variants of graves. Someone can just go around in an early town and cause an area to be cluttered with bones that don't despawn. 

If people want to keep bones around it should be either in graves or baskets.

**Comment by Kaden56** [comment]
Even basket bones should despawn and just turn back into a regular basket over time. In real life the body decays or you burn it. But the grave of the person remains there forever so you can remember them. So in game the marked grave should be the only thing that doesnt decay because its a marking to remember the person who passed on and has decayed.

**Comment by ShadyAbusesComplexWebappsOneFatalFlaw** [comment]
Ima deface your bones irl
