### ISSUE TITLE
BALANCE ISSUE: Buff Domestic Milkweed

### ISSUE THREAD

**Issue by SoloAceMouse** [jasonrohrer/OneLifeData7#1145]
![Milkweed Issue](https://github.com/jasonrohrer/OneLifeData7/assets/147592460/94296a41-dbea-4ddf-8457-4b3128cc1884)

Milkweed is widely regarded as an ineffictive crop to grow, since the wild and domestic variants are identical. In many cases, it is considered detrimental to grow milkweed in early towns, since the water cost of appreciable milkweed farms greatly exceed other crops.

Other plants, such as onions or carrots, have far greater yields in domestic variants than their wild counterparts [which mirrors the real-world agricultural practice of domestication for higher yields]. Milkweed should receive the same attention as other plants.

Please increase the yields of domestic milkweed to match other plants in the game, which will improve crop water-cost balance and make farming milkweed a less controversial subject.

Thank you,
SoloAceMouse

**Comment by SoloAceMouse** [comment]
Just for fun, here are a couple anti-milkweed memes that I made to discourage people from farming milkweed, since it's currently quite inefficient. Hope you get a chuckle from them. :)

![Milkweed Madness](https://github.com/jasonrohrer/OneLifeData7/assets/147592460/24f15311-ad5c-4b78-848b-b8a67b7efc48)

![anti-milkweed PSA](https://github.com/jasonrohrer/OneLifeData7/assets/147592460/8c094244-b8c7-4b0a-b58e-87a2ee8cb768)

**Comment by Tarr-OHOL** [comment]
I think the easiest change is to make stage two (instead of three like original) to go back to the fertile stump. When you picked a stage three milkweed it grew back after an hour which does reintroduce the issue of lazy people picking early but would then give each stage a use. 

Stage 1 = quick decay. 
Stage 2 = Regrowth
Stage 3 = Seeds

**Comment by MooseSeven** [comment]
The way milkweed is balanced right now is the reason why early towns (pre pen) often have lots of naked people, or advanced clothes looted from old towns. Making simple clothing just isn't a priority when farming milkweed is a pain, and the town also needs hatches (and hoes in case of a late forge), backpacks, arrows and bows, and later carts, boxes and slot boxes etc. Making milkweed more accessible would be a welcome change, and perhaps the fashion style of a town would not skip stages as easily.

**Comment by Arcurus** [comment]
Getting 2 or 3 Milkweed from one row would be much better.
Also it should give a hardened row if you pick it.

Alternative let all Mikweed stumps grow back after one hour and add a hand (or hoe) transition to remove the stumps

**Comment by jasonrohrer** [comment]
Well, the idea here is that there is no such thing as "domesticated" milkweed.  It is a wild plant, and thus behaves like one after you plant it.  In fact, it is exactly the same object.  It will go through the same cycles as regular wild milkweed.

This is a bit like planting trees, most of which do not have domesticated versions.

It is a tough trade-off with early clothing (which would actually cause you to consume less food if you had it).

But it has been this way in the game forever.  Milkweed is just one of those precious things.... just like in real life.

**Comment by SoloAceMouse** [comment]
And yet, domestic fibrous plants have been grown for thousands of years for production of cord, twine, rope, and thread.

I can't help but be disappointed.

**Comment by DougLefelhocz** [comment]
"It is a tough trade-off with early clothing (which would actually cause you to consume less food if you had it).

But it has been this way in the game forever."

[No](https://onehouronelife.com/forums/viewtopic.php?id=6365).

"The Eve game was tuned around it"

Since the Eve game has gotten tuned around it, there existed plenty of reason for Eves to consider starving children when player count surged.  I've sometimes said "FOLLOW OR DIE" to some of my children when walking around in the wilderness.  But, often I'd end up going back to them, because they look like they use the default client and can't see me.  Or maybe they misclick.  However, with [this many bushes](https://imgur.com/ZWt4IXb) instead of [this many](https://imgur.com/K5s8cda) bushes, there isn't time for anything like that.  Baby not follow, it ends up rational that the baby has to starve.

And then later, because of the low levels of burdock, going out and hunting rabbits requires even more time, or needing to venture into a land where a wolf or bear might bite them.  The result?  The only pie worth cooking becomes carrot pie... meh.  Instead of a family having some rabbits for rabbit pie, rabbit carrot pie, and carrot pie possibly, they end up stuck on carrot pie. 

Also, then when someone makes a sheep pen instead of sheep having function, it becomes questionable if it was worth it at all.  Because there end up so little berry bushes that feeding sheep becomes questionable over letting some new player eat a berry off a bush.  

And it can end up looking something [like this](https://cdn.discordapp.com/attachments/785795746888024105/1191817352023638016/image.png?ex=65a6d167&is=65945c67&hm=85edaeea186483f06ec2ccb9264f6dfe51050bb106196aee27776a173cd787c8&) after [9 generations.](http://lineage.onehouronelife.com/server.php?action=character_page&id=10063597&rel_id=10063597) (and ceasing to have children due to a bug in the server direction code).

And for other families must absolutely rush through the water branch of the technology tree, because the farm must get expanded rapidly or they will starve.
