### ISSUE TITLE
Suggestion: Donkey Town and War

### ISSUE THREAD

**Issue by oholsuggestions** [jasonrohrer/OneLifeData7#1150]
What if Donkey Town was allowed to become a really town? As in, same gameplay allowed as in the rest of society, but only accessible to people with a certain amount of curses? That way they could grief each other without bothering other players.

Since their banishment takes at least five years, they could be born to each other and build their own community. Multiple accounts would be pointless as they would all just respawn in Donkey Town eventually. 

Anyone sent to Donkeytown would automatically have the last name Donkey. So there's an easy identifier which could be used to limit certain interactions -mainly using the radio, but restrictions could exclude more actions to make it more difficult to progress-.

If their spawn point is far enough away, that it would take multiple generation to bridge the gap between Donkey Town and the rest of society. Between in-fighting and the distance, a confrontation between Donkeys and society shouldn't be frequent at all. **However it would be possible if the Donkeys work together over multiple generations.**

The war sword could be used between Donkeys and society, instead of individual families. And if Donkeys ever end up wiping out the rest of society, perhaps the Eve's spawn-point could be moved again by a huge distance.

**Comment by Tarr-OHOL** [comment]
There are so few players as is that being an actual "banned" account is essentially just the ultra cursed who already have other accounts (unless you're shady and his mom won't buy him another.) These people aren't even always stuck there depending how dumb they are to get there in the first place. 

Donkeys have had towns and you know what happens? They grief themselves. I am sure you're not going to be surprised by this but people who ruin things for others don't spare each other lol. 

Donkeys can't have radios since if they wanted they could spam slurs over it and no one could stop them. Donkeys cannot and should not be allowed near anyone else. What purpose is to block someone if they can just come back with fancy black bubbles? People would grief to get this "cool" chat bubble. 

People have literally walked a normal family to donkey town for the sole purpose of kicking in their teeth. Hilarious, but that is not good for either party. 

PVP or conflict in game should come from other families and not the assholes of the game lol. Keep the assholes to trolling themselves or ask them to fork over more money in no way shape or form should they get to grief then have the chance to do it again.

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/773c96e9-0041-4f61-8723-fc8e02f85be7)
