### ISSUE TITLE
Suggestion: being able to dig up seeds planted in dry tilled row with shovel.

### ISSUE THREAD

**Issue by bee0ela** [jasonrohrer/OneLifeData7#1158]
Problem: people often put random seeds (mostly carrots, beans and milkweed) on tilled rows that were already "designated" for planting another stuff (e.g planting beans on 3 rows of a full potato garden, messing up with the farm organization and overplanting some items).

Not only that, but we can also plant wrong seeds by mistake and then we can't help, but need to water the whole thing and wait for it to grow up and pick it up in order to clean the space and only **then** plant what we really wanted. It takes time, resources (soil, hoe, water) and patience.

Someone on Reddit pointed out the shovel as an issue, then maybe it doesn't need to be a shovel, but it could be a skewer? I just think we could have a solution for this.

Solution: Shovel or Skewer + Dry Planted Stuff = Deep Tilled Row

**Comment by jasonrohrer** [comment]
Eh...  once you plant a seed in the ground, it's pretty much over.  I guess you could till it to restore the row without wasting the water, but you really can't get the seed back and use it again.

I'm open to the idea of destroying a dry row, with a shovel, to turn it back into unplanted.... WITHOUT getting the seed back.  However, I'm guessing that players won't like that, because it's easily griefable.  You plant stuff, than walk to get water, and some idiot digs up everything you just planted.

Maybe this is no worse than just tilling a bunch of rows, and some idiot goes and plants peppers in all of them...

Anyway, I will close this issue now, and you can confer with the community.  If there is consensus that destroying a dry-planted row to re-use it (without getting the seed back out) would be useful, please post a new issue and I will add that.
