### ISSUE TITLE
Humans have no enemies

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLifeData7#1160]
The only thing I fear in this wilderness is my hunger bar.
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/399140aa-5c78-42c1-98b5-d7e3e5530fbf)

**Comment by Shadie116** [comment]
I got a nursery and tools in a single life. You might as well just remove bears entirely and keep the cave. There is no challenge to development of towns.
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/ebdf2a8e-db3d-40c6-ae72-e3f14b59087d)
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/65e8e01f-3bb8-4d31-9e58-c53a842772ba)
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/f5342b9f-bf17-4a0b-bf87-dd50bb0ddf79)
Serendipity Reigns, experienced players could literally just spawn in randomly and start building a top tier civilization without any problems.

**Comment by DougLefelhocz** [comment]
Bears can kill players, wolves can kill players, boars can kill players.  Mosquitoes can kill players, especially if they are fully clothed.  Players (at least those without a zoom mod and a mod feature to make dangerous animals more visible), can easily die from these animals in the wild, or early on as Eve or child of Eve.  In fact, I'd say that easily more often than not, I'll have some child die to boar or wolf when I'm an Eve.  And I know that when I played with Awbz mod, avoiding boars could sometimes be tricky (and wolves have gotten me often enough due to a lag issue even with Hetuw mod).

The other day as a Lancaster, granddaughter of Eve, I was out by an iron vein, trying to lure a bear away from the vein, when a baby popped out.  And quickly became bear food, before I could pick it up.

So, it's simply not true that human players have no enemies in this game.

Stop using zoom shadie116.

**Comment by Shadie116** [comment]
yeah sure whatever you say buddy, just think of it from a totally different perspective. You got this big popular squad of people advertising a zoom mod. That poses abit of an issue Uhh ohh, now the game is easy for everybody. You got this big big Christmas playerbase or whatever doing, idk and now they all got zoom. Before you were here the game was more challenging, as the nature of survival games should be. People were talking about OWHHOHH, the game is too hard for newer players, THATS THE POINT. I bet they had wolves trying to maul eve to death wayy back when. we lived in caves because it was soo dangrous

**Comment by Shadie116** [comment]
Did you know that bears once came after you? She had to have been a pendejo to run into a bear

**Comment by Shadie116** [comment]
My point is, my point is bolted to the dam ground
