### ISSUE TITLE
Newcomen Pumps and Engines

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLifeData7#1165]
DemonicBlack pointed out a while ago that it's not consistent that the tire on the multipurpose newcomen engine does not break, while the tires on the newcomen pumps does break.  Both tires are the same part on a newcomen atmospheric core.

A possible advantage of the multipurpose newcomen engine breaking would be to length the time of the early game, and so that diesel engine making depended more on members of families working together or leaving their specialty resources for others to use.  Perhaps also it would lead to a more difficult decision about tires... "do we use these tires on a multipurpose newcomen engine to make a diesel engine and try to import water from ponds/wells, or do we use those tires on our newcomen pump?"

**Comment by SoloAceMouse** [comment]
I strongly feel that adding a tire consumable requirement to the Multi-Purpose Newcomen would be a mistake.

The current water cost of the tooling Newcomen variants is one bucket of water per use. Since a tire lost from the well is an opportunity cost of 3 buckets of water [4 buckets minus one for the next cycle], this change would result in the Multi-Purpose Newcomen having it's water cost increase four times as much as it currently is.

Having to experience **four times the water cost** per cycle is not something I think would be good.

-----

I don't think the proposed change would do anything more than make the mid-game tedious and more frustrating. While I enjoy difficulty when it is rewarding, I feel like this difficulty increase would not be rewarding but instead unnecessarily harder. 

For myself or other experienced players, making the game more difficult might be of interest, but these difficulty adjustments also affect novice and intermediate players as well.

**Comment by Tarr-OHOL** [comment]
Making things tedious for the sake of tedium is bad. Having a (slightly) annoying cost of 1 basket of charcoal and ten water already makes advanced things less new player friendly as being slow is discouraged when you’ve already got a somewhat quick time limit to work a Newcomen. 

We want new players to learn advanced stuff and making mistakes is okay and part of learning naturally. Making things more costly leads to gatekeeping and now allowing new people the chance to learn. 

You know how to play the game and while this would negatively affect you, it would much more negatively mess with new people.

**Comment by Butterbraugh** [comment]
I disagree strongly with the opinion that Newcomen seal use is inconsistent. When drawing a heavy load and actually pumping liquid from deep underground the rubber seal is destroyed with both the Newcomen Well and Pumpjack game objects. This makes perfect sense. 
Operating a mechanical device such as the Multipurpose Newcomen or Drilling Oil Rig does not place massive strain on the seal, therefore it does not break.

The way Newcomen's operate is not an issue. This games issue's are lack of more late-game content. For example, an efficient diesel driven Multipurpose mechanism that consumes fuel on per use basis similar to sprinklers and plows.

**Comment by DougLefelhocz** [comment]
I appreciate the responses from SoloAceMouse, Tarr, and Butterbraugh.

Shadie116, Jason can speak for himself.  He can also change something with respect to what got brought up, or just close this issue without any comment.

If you want to explain his way of thinking, then you would do better to refer in some way to something he has wrote or something he did.  Speculating on how someone thinks can lead into all sorts of misconceptions, and it's even worse when the person speculating doesn't have enough information.

Also, I don't understand how resetting the newcomen engine would be possible, if the tire disappeared after the fire got used.

**Comment by Shadie116** [comment]
you take off the multi part and add a different one to reset the durability

**Comment by Shadie116** [comment]
or just take it off and put it back on

**Comment by Shadie116** [comment]
unless jason will do it for the heck of it

**Comment by jasonrohrer** [comment]
Good point, Spoonwood.... that is a bit of a "magic" difference in there only for game balance reasons.  But there are a bunch of things in the game like this.  I do want crafting to be as realistic as possible (20 steps to make a fire, etc.), but sometimes that has to be sacrificed on the altar of game balance.

This sacrifice mostly happens in terms of how long something takes to make (the time delays), or how much water something gives, or how long something can be used before wearing out.

Usually the aesthetic of "real-world-accurate crafting steps" isn't sullied by this too much.
