### ISSUE TITLE
Suggestion: WASD controls

### ISSUE THREAD

**Issue by thebbbomb** [jasonrohrer/OneLifeData7#1168]
One of the most prominent complaints in the recent negative steam reviews for the game pertained to the confusing controls. I'm nearly positive that having an optional WASD control scheme would improve player retention, seeing as mods that allow WASD input have been such a quality of life improvement for me and most of the regular playerbase.

**Comment by jasonrohrer** [comment]
This decision was made early on to reduce message traffic.

You click once, and a long path is defined, around a bunch of obstacles, etc, and sent to the server as a single message.

WASD, where you micro-manage your path, requires constant messages.

Granted, some players spam click, but they don't need to spam click in order to play the game.  The tutorial also shows how path-finding is automatic, even around complex obstacles.

The one degen case for click-to-move is if you're making a long journey in one direction, and hold the mouse button down near the edge of the screen.  You then request a lot of short paths right in a row, where WASD would seem to be only one message (hold left key)

However, WASD controls aren't as simple as that, message-wise, because the CLIENT is actually the one doing the move timing and managing player position.  The server just makes sure the paths submitted by the client are consistent, connected, etc.

So if you say, "LEFT KEY DOWN"... and then the player starts walking left, and then later you say, "LEFT KEY RELEASED", how far does the server think the player walked in that time?  What if the client thinks they went a different distance?  Well, the server has to be right, so then the client would snap back to the server truth, which would be jarring.

If you send a path to the server (this is where I want to go), the server doesn't really care how long it takes you to get there, as long as its not too fast.  It just knows where you will end up.


The mods are all "hacking" WASD controls by sending a bunch of really short paths.  The game, server, and protocol wasn't designed to handle this.

In fact, the whole protocol is designed in a very loose, asynchronous way, which is why it remains mostly playable even on very slow and spotty connections (where realtime movement with WASD would not be).
