### ISSUE TITLE
Allow Plaster flooring and have it colored like the walls.

### ISSUE THREAD

**Issue by Rin0de0la0crypt** [jasonrohrer/OneLifeData7#1171]
This is a change warranted by the lack of floor verity currently in the game, and with the change it would enable more creative freedom for builds. One bowl of Plaster on a floor stakes gets you a Plaster floor.  One bucket of paint on floor gets you a colored floor. It's warmth can be simular to stone floors. As for its break down process it can be simular to the Plaster walls but require an adaze because it's a floor. The by product of that can be rubble or something else.

**Comment by DougLefelhocz** [comment]
What lack of floor _verity_ in the game?  Floors do _truly_ exist.

>  One bowl of Plaster on a floor stakes gets you a Plaster floor.

1. This would have to get drawn.

2. It would have to get coded and also in line with the rest of the code.

3. People making plaster floors would put more pressure on the water supply.  So, it could lead to an in-game problem, if wells weren't buffed also and they became popular.

The Github is for in-game problems, something arising from an in-game problem, or bug reports (or requests to see if there is a bug).  Suggestions like this better belong on the forums or the reddit.

Also, clearer language can help a lot.  If you mean "variety", but say "verity", that makes it more difficult to understand what you're claiming.

If this gets closed fast, it's probably because it's just a suggestion/request.

As charitably as I can imagine... perhaps some people get bored mid-life and log out, because of the lack of floor variety.  Thus, lack of floor variety might signal a weakness, since I don't think Jason wants people to log out *just* because they feel bored (I could be wrong here).  But still, that's a rather general claim, and not suitable to this github.  Plaster floors isn't the only way to increase floor variety also, as 2HOL and MoeLife demonstrate.

**Comment by Xefjordx** [comment]
Regardless of if this is the right platform for posting such a suggestion. I do like it as it provides a substantial amount of cosmetic endgame variety as well as serves a practical purpose of further helping color code rooms and functions in developed towns. It may be water taxing, but it also probably wouldn't be used unless a town is already quite developed. If a town starves itself making plaster, well that's just darwinism. 

That's my take.

**Comment by Tarr-OHOL** [comment]
> What lack of floor _verity_ in the game? Floors do _truly_ exist.
> 
> > One bowl of Plaster on a floor stakes gets you a Plaster floor.
> 
> 1. This would have to get drawn.
> 2. It would have to get coded and also in line with the rest of the code.
> 3. People making plaster floors would put more pressure on the water supply.  So, it could lead to an in-game problem, if wells weren't buffed also and they became popular.
> 
> The Github is for in-game problems, something arising from an in-game problem, or bug reports (or requests to see if there is a bug). Suggestions like this better belong on the forums or the reddit.
> 
> Also, clearer language can help a lot. If you mean "variety", but say "verity", that makes it more difficult to understand what you're claiming.
> 
> If this gets closed fast, it's probably because it's just a suggestion/request.
> 
> As charitably as I can imagine... perhaps some people get bored mid-life and log out, because of the lack of floor variety. Thus, lack of floor variety might signal a weakness, since I don't think Jason wants people to log out _just_ because they feel bored (I could be wrong here). But still, that's a rather general claim, and not suitable to this github. Plaster floors isn't the only way to increase floor variety also, as 2HOL and MoeLife demonstrate.

I really think you don't understand some of the nuances of creating content. He would have three different easy options for developing colored floors:

1). He could do like me and just recolor the plastered floor. This just requires adding transitions and while it does "create" a new object from each color the difference between the original floor and the colored variants are just color options in the editor

2). He could create ONE new drawing and then color each different one in the editor. Still needs a sprite/object done but it's easier to turn one drawing into a bunch of colored ones.

3). He could make EACH one a separate drawing but this would take a lot more time if he drew and colored everything before scanning it in to the editor. 

I'm not saying it's easy to do this with a bunch of colors but it does take time to do this.

**Comment by Shadie116** [comment]
fr, they got floors looking like the entrance to kernels plantation.

**Comment by Shadie116** [comment]
Check out this ohol ass floor plan 
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/4b13dc21-cfef-4969-b45f-559511beaef0)
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/18a5b3f4-06b3-42bb-940f-99602de9549f)

**Comment by jasonrohrer** [comment]
There's a reason why there are no plaster floors in the game...

Plaster just isn't used for floors.  It's too soft, and would wear down from walking on it.

In real life, floors are made from wood, stone, tile, brick, concrete, metal, linoleum, and plastic.

You also *usually* don't paint floors, for the same reason.  Well, most sane people don't paint them.  I've seen some painted floors on occasion, and they look like crap because of course the paint wears off.
