### ISSUE TITLE
Donkey Town's Sentence Is Unjust

### ISSUE THREAD

**Issue by AccountAbandoned** [jasonrohrer/OneLifeData7#1195]
I decided to transfer this to an entirely different issue. 
This is just an excerpt

**Comment by Shadie116** [comment]
i agree, really the game just needs to fix cursing. Donkey town is arguably worse than it was without the biomes. I mourn for the days donkey town was just an empty wasteland for griefers to wait out their punishments in solidarity with only the small chance of anybody coming to see them. 3 months was enough, now you get to be trapped for five years

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/15a6ef0d-2436-48f6-b805-0489b219a1c5)
could have should have fooled me 🙄 fooled my entire group

**Comment by Shadie116** [comment]
you practically permabanned an entire group of 7 people (and more), all you had to do was change a value
source: https://github.com/jasonrohrer/OneLife/issues/744
source 2: https://oholcurse.com/
that's 7 people who cannot play for 5 years
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/8db94899-aae4-4ac5-b251-e0ff74aea15e)
and people spend most of their time at towns so that update won't do a thing
(pz fix)

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/1c6f3c0f-91e7-4af5-9ce3-e0131a4bf31f)

**Comment by Shadie116** [comment]
now lets see my score after a period of about a year: (unplayable). Any updates you make to dt only instigate the actual problem and provide false hope. In reality nothing really changed because its going around the rim of functions within the game that nobody even uses. I've been arguing this anticipated result for months on end throughout my entire year and to the next.
![image](https://github.com/jasonrohrer/OneLifeData7/assets/126846097/2d290bb3-3d21-4ec5-8239-f382fadc9e4e)
So what I'm calling is for you to change the curse length entirely so there won't be so many donkey town issues. If you're in a place you're not able to really play in for five years its going to get boring, it wasn't too much of an issue when people were spending 3 months in isolation.

**Comment by Shadie116** [comment]
If I'm being real honest I'm also doing this for my friends as well because they got the most rotten part of the apple.
