### ISSUE TITLE
Plane doesn't travel between landing stripes

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#146]
Plane doesn't seem to work
https://imgur.com/a/xpVWslp

I tried traveling from one landing strip to another, other landing strip was 1.1 k south i tried taking off from road south and north of the current landing strip but
each time i keep going to the departing stripe instead of the destination one

It seems like the plane only goes to the latest created landing strip and impossible to travel between the stripes

Also on another server i landed in the middle of nowhere
https://www.youtube.com/watch?v=_-yu2tbEchI&feature=youtu.be
There was two landing stripes on server (that i was aware off) but i landed in a place with no landing strip, dont know why it happened only odd thing is the sound of plane running out off fuel just before take off, which is weird since i just added gasoline to it

**Comment by Dodg-e** [comment]
Was able to fly between landing stripes by making shorter roads and going in the right direction.

Dont know about the second issue though

**Comment by Tarr-OHOL** [comment]
On my crashed flight I was failing to find a landing strip that was 2.8k west, 300ish north while heading west. Most of my trips heading north would end up taking me where I wanted for the first few and afterwards it would return me to the departure point instead of taking me to where I was wanting to go.

Seems off that specifically heading somewhere (a place I even know the location of by heart) I know has a pad and even going the correct direction would cause me to crash instead of taking me home. Hope you get this all settled soon as planes are a really great addition to the game.

**Comment by jasonrohrer** [comment]
I think this was hotfixed a while ago.
