### ISSUE TITLE
Dug Potato - Last Use still breaks shovel

### ISSUE THREAD

**Issue by betalpha8** [jasonrohrer/OneLifeData7#174]
the fix for #125 missed the last use transition.

Consider also the new inconsistency with dropping "shovel of dung"
(seems unintended considering also your iron thread*** had math assuming one shovel use per compost)
***https://onehouronelife.com/forums/viewtopic.php?id=4315

**Comment by betalpha8** [comment]
All other tools' last use appear to complete their action while the tool breaks.
With the intermediate shovel cases, the last use is eaten immediately.

**Comment by jasonrohrer** [comment]
Yes, that is necessary for the shovel, because its "use" involves ending up with something IN the shovel, so if it breaks, the action cannot complete (there's no shovel left to hold the dung or potato).

For the axe breaking, the action can complete, because the chopped wood ends up on the ground, not "in" the axe in your hand.

The shovel is a special case.

As for the double-use for dung-shoveling, that is true.

But I was only trying to fix potatoes here.  I don't want to rebalance long-term iron usage in farming right now.
