### ISSUE TITLE
Facial hair on some character models blocks smile

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#187]
The facial hair on some character models can block your character's smile or other facial expression. 

One example:
https://puu.sh/CTdHp/ba8bc21cfe.png

There's a model with a full mustache and beard that's worse.

**Comment by jasonrohrer** [comment]
Yes, this is the price of proc-genned stuff like emots, which is why I was reluctant to add them.

The characters themselves are all hand-made and hand-positioned, but the emots must "fit" the characters the same way, because they apply to all characters.

The mouth of this character is under his beard...
