### ISSUE TITLE
Seeding carrots decay

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#207]
Reopen of issue #200, 

The weirdness about carrot seeds isn't that they decay in 5 minutes, that's fine, it's that seeding carrots decay after 10 minutes.

https://onetech.info/401-Seeding-Carrots

No other plant disappears if it isn't harvested, and the soil is also lost.

**Comment by jasonrohrer** [comment]
Yes, growing carrots destroys the "hardened row," and leaves nothing behind.  There's probably a good reason for this (I had a whole spread sheet for the food meta when I designed it, and carrots took 1 soil plus two tilling for a reason.

However, I will fix it so that the seeding plants don't disappear.
