### ISSUE TITLE
Missing transition to stake Empty Domestic Gooseberry Bush

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#214]
You can stake an empty wild gooseberry bush but can't stake an empty domestic gooseberry bush
https://onetech.info/279-Empty-Wild-Gooseberry-Bush
https://onetech.info/1135-Empty-Domestic-Gooseberry-Bush

This makes it rather challenging to remove bushes in populated towns. As soon as a bush becomes languishing someone usually adds soil to it, a natural thing to do. But then you can no longer remove it. You must water it, wait 8 years for berries to grow, pick all the berries, and wait another 2 years to become languishing, and then _hopefully_ be there to stake it in time before someone else adds soil.

Also, I find it kinda visually weird that a languishing bush is an unhealthy looking dark color but just adding stakes turns it back into a healthy color.

**Comment by jasonrohrer** [comment]
I did fix the color

Fixing it so that you can stake empty could be exploited to speed up the transition to languishing (currently 2 minutes).  If staking makes them languishing.  If staking doesn't make empty languishing, then I need to add a bunch of other transitions just for empty.

So, for now, I'm leaving it so that you must wait for languishing.  Talk to people.  Guard the bush.
