### ISSUE TITLE
Can't eat raw onions, tomatoes or peppers

### ISSUE THREAD

**Issue by thaulos-bolsens** [jasonrohrer/OneLifeData7#230]
Can't eat raw onions, tomatoes or peppers.

**Comment by HimitsuGato** [comment]
I think peppers make sense not edible since they aren't very nutritionally dense. Onions should be edible to be consistent with wild onions. Tomatoes could be more complicated, like serving tomato slices with salt. More discussion over at https://old.reddit.com/r/OneLifeSuggestions/comments/b7ulsz/edible_tomatoes_pretty_please/

**Comment by jasonrohrer** [comment]
Toms and onion have been fixed.  Peppers are hot and meant for spicing.
