### ISSUE TITLE
Corner property fences are awkward to repair

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#263]
You need to be standing N/S/E/W of an object to interact with it, making corner fence repairs awkward. While you can repair other fences from within your land, you need to exit your property and repair the corner fences from the outside. Also, if a fence is surrounded by other fences on all sides it cannot be repaired at all.

Just to be clear I'm referring to any property fence placed in a corner.

**Comment by futurebird** [comment]
Yes! It takes up a lot of walking.

**Comment by jasonrohrer** [comment]
Yes, this is annoying... but it's pretty tricky to fix.

Diagonal access is not allowed in the engine, because it generally looks weird.  The client code doesn't even support a diagonal action (the player would have to "bounce" diagonally).

I'm thinking of lateral solutions to this problem.

What if repairing a nearby horizontal or vertical fence automatically fixed a neighboring corner fence, through tap-out?

So you wouldn't even need to manually fix it.

**Comment by miskas9** [comment]
I was about to propose the same. repairing a fence tile also repairs its adjacent tiles.

**Comment by jasonrohrer** [comment]
Well, I'm only going to do the corners for now, so it's not so surprising.  Otherwise, as you went down the line, you'd have to skip every-other tile.
