### ISSUE TITLE
Burying graves is griefing-bad

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLifeData7#268]
Shovels quickly break from burying graves. I appreciate the aesthetic of burying and wish we could do it instead of having yards of bones, but since there's no real benefit and the shovel breaks quickly, it's awful and is a form of griefing/noob-trap. It's a similar problem to the old potatoes but even worse since you can't eat buried graves.

A buried grave does decay in 1 hour instead of 2 hours for bones, but often you don't know how old a random pile of bones are. Burying bones older than 1 hour will actually increase how long it takes to decay.

**Comment by futurebird** [comment]
Related forum thread:
http://onehouronelife.com/forums/viewtopic.php?id=6232

**Comment by Devroll** [comment]
Yeah, I think the length of decaying should be shortened more, because that’s the point of grave burying, and it becomes flat land, and the graves could be walked through so the graves become less of an obstacle.

**Comment by Spodnie** [comment]
Yes, some people are burying all bones (even /die babies) with no reason.
It's a bit weird that burying people may be considered as griefing tho, it shouldn't.

Maybe this action is just too simple and should require 2-3 more steps?

**Comment by Devroll** [comment]
I think another option should be cremation, like burning the body, putting ashes in a bowl and cover with plate, then burying it? Make it faster to decay.

**Comment by Tarr-OHOL** [comment]
Just make it like wolves. Don't let them be dug back up and greatly shorten the time it takes for the grave to despawn with no headstone. This way people can't use normal graves to grief besides using the shovel charge once vs destroying a shovel instantly.

**Comment by voy178** [comment]
Yes, Shorten the time and remove the ability to dig them up again. It makes more sense than digging up bodies without consequences like deceases.

**Comment by Devroll** [comment]
Maybe hungry work?

**Comment by Spodnie** [comment]
voy178, removing the ability to dig them up would sucks. We need to be able to dig them up if they block necessary space.

I think hungry work would sucks too if we also needed hungry work to dig them up - That would be an easy way to grief.

This action is so simple that even biggest noobs do it, that's why it's a common problem. If it required more steps it wouldn't be a problem anymore I guess.
At least one more step - add stakes to bones and then use shovel - could possibly work too.

**Comment by Devroll** [comment]
Or something like the fences, where the grave can be taken down by anyone (so you have to put the grave in a more hidden spot and not block the public spaces) until you wait a bit and then be able to erect the gravestone, and you need shovel to dig them up, and also hungry work to make the gravestones so people don’t spam the graves and we waste a lot of shovels.

**Comment by Tipy1802** [comment]
How to solve: using shovel on bones doesn't use up the shovel

Do the same for potatoes, really Jason why did you nerf potatoes for no reason at all, don't you remember how they were literally a meme back when diging potatoes costed iron and back then iron was way easier to get. The food bonus isn't enough since by gen 30 is gone

**Comment by laccy** [comment]
my main concern with graves is that they are way too close to towns especially when there is a fence they occupy 25% of the land. their placement is bad and annoys me a lot. Some players who do the graves, even bring back the bones to be in the same place as others so it even takes up more space. Also, most veterans understand that it breaks the shovel but newbies who do it, don't understand placement or iron needs, so they dig them in their spot they died or where they were carried first, they don't leave enough space for kilns or other buildings. So removing them is necessary, or just relocating it. 

I would suggest a minimum distance from the well of the homeland, like 30 tiles. Or some special ground to be made, like with fences, some person should mark land where bones can be buried, at least 4x4 then graves go there.

There is a problem with the flat rocks since they are needed for smithing, cooking and fast roads, so makes graves even more annoying.
This could be remedied with anvils, pans and stoves, roads could have some sort of basmac or asphalt upgrade but that's way more complex.

The way I see grave digging is purely cosmetical and shouldn't use resources that fast, it was a problem like forever, graves are the most common items in every camp. Some people even suicide seeing too many. 
I would suggest that gravestones should be permanent, but cheap, like fences, you could carve out one from a flat rock then place it until you need it and then it decays.
It can be retrieved by digging out a grave but can only be used on other graves.
Alternatively, we could have other grave markers like crosses, I guess you don't want to make it to Cristian only game, so it should be like a signpost T or reverse L shape marking with the relation.

Also it should not use up the shovels. People do it to pay respects, not to gain anything from it, but wasting resources makes it a bad action.

One more alternative could be a viking burial where the corpse is set on fire and leaves ashes behind which could be buried into a small slot of a wall specifically made for this.  It could hold 4 ashes and have a small mouse-over text.
This could free up space and make towns look nicer. Graves that are left behind should decay faster we got more, people got so fed up they don't even move sheep bones which have logistical value to them.

Distance- is realistic that it's un-hygienical to bury people close to living people.
Fast and easy- since newbies are doing it
Cheap- since it's not an activity that brings profit, also shouldn't take away resources from other activities to prevent conflict

let those newbies bury people and veterans have no reason to be mad about it. We go more dead people with these food changes.

**Comment by Arcurus** [comment]
**in all cultures taking care of the dead is valued high, but not here.** 

Why not give some respect to the death and encourage to bury.

Like double negative gene score if the corps is rotting and half good

The charges of shovel could be increased drastically. 

for a fresh grave a 1 minute timer could be set before it can be undigged again.

In the gene score overview it would be nice to see how your body has been taken cared.

Maybe even a way to communicate with some letters with the dead on the grave would be nice i guess people would love it.

**Comment by Devroll** [comment]
ooooo i like the gene score thing. Gene score would be a good way to encourage players to do a lot of “useless but gives happiness” things. Like for example, theres not really a big reason to make bonsai trees, wear colorful clothes, or plant flowers, but if you gave a small gene score, players will be encouraged to make “happiness” things that will otherwise be a useless, waste of time
