### ISSUE TITLE
Something's off about Bears

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLifeData7#314]
I noticed this the other day while hunting some bears, something is definitely wrong with their targeting AI. 

Half the time, despite being literally right next to the bear [on an object] and being literally the only person around for dozens of tiles, it would randomly run off in the opposite direction. I observed this multiple times, all while being 100% within the bear's 4-tile walking radius. It's rather odd.

 Normally they'd simply target me back and forth across the item, but several just started running in a different direction and continued to ignore me even when I came after them. 

I noticed this while luring a bear away from town as well. Half the time it'd focus on me, but the rest of the time it'd just suddenly change direction and wander off. I don't know if it's a sudden blip in the server not registering the player being near the animal, or if there's something else up with it.. but I know other players like Tarr have also noticed this strange occurrence. 

And before you propose the idea of it having eaten mutton, I'm aware fed grizzly bears are random movement and not chase. But there was no mutton nearby at all. This was in the middle of nowhere with freshly spawned bears from their caves. All of them were considered 'hungry.' Nobody else was nearby.

**Comment by Tarr-OHOL** [comment]
Bears and other animals have been off for months. I am not sure what caused this change but as you seen with the bear deciding to walk off randomly you can't consistently lure animals like you used to.

Bears will go in random directions
Domestic mouflon will decided to run when they should follow
Horses will charge at you instead of flee.
Basically all animals suffer from whatever change was made a while ago.

**Comment by hetuw** [comment]
i can confirm, animals sometimes walk in random directions,
sometimes they even stop walking and just stay there
