### ISSUE TITLE
More/better storage (what does this mean?)

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLifeData7#319]
Please fill this issue with comments explaining what you mean when you complain about lack of storage.  List items that can't be contained that should be, etc.

**Comment by Dodg-e** [comment]
Issue with baskets in box is you have to remove the basket then remove the item from the basket and finally put the basket back in the box.

So having storage that you couldnt put baskets in but would have 6-8-10-12+ slots would be much better, dont need a 100 slot container.

It could even be specific storage for different items, like a pie stand, barrels to put corn, tomatoes, peppers etc. A tool box to put all the small mechanical pieces like fuel nozzle, piston, steel valve etc.

A closet to put clothes in or even a hat hanger specifically for hats.

etc...

You get the idea.

It would help with organization since you would now what type of object is where.

**Comment by Don-Holm** [comment]
Item#1: Seeds
Seeds are collected in clay bowls, and stays there until you plant them. A box that fits big amounts of seeds is required.
Item#2: Milk/liquid latex/Salt water/etc
Same as water, you can't store liquids in buckets until you use them, as buckets require "ropes" to craft and expensive to craft, so a tank that stores those liquids is required.
Item#3: Wheat
Threshed Wheat should be collected in barrels, as they take a lot of space and hard to move places
Item#4: Omelette/French Fries/Bean Burrito/ and lot more
Any type of food with "Clay Plate" that cannot be placed in baskets or boxes, could be placed on a table, or "big plate" that fits more pieces!

I suggested a few, but I'm sure you could understand a bit more of how we need items stored.

**Comment by cloudiirain** [comment]
On the forums, Jason, you mentioned the problem of server load for having lots of generic storage. 

Wouldn’t this be resolved if instead there were specialized storage containers (e.g. grain silo)? I believe(?) currently you use brand new objects for each element of a stack (e.g. bucket with 2 bowls of water => bucket with 3 bowls of water), however this is quite tedious.

I know this might be a lot to ask for, but wouldn’t your coding be so much easier if you stored a generic “counter” parameter with each object in the database? And then serialized this counter when sending data to clients? You can store it as a short so the impact on bandwidth is minimal.

For instance, carrot (counter=1) would be rendered as a single carrot on the ground by the client. Carrot (counter=5) would be rendered as a stack of five carrots. Shallow Well (counter=4), Iron Mine (counter=3), etc could all have different meanings that make stackable data a lot easier to handle.

It would make our lives a lot easier if most items of the same type were stackable (or containable in a specialized container that stores only one object type).

**Comment by Booklat1** [comment]
lack of storage means
1 Some stuff cant be easily stored while being commonly produced (grain, for example) and
other things cant be stored at all (foods on plates/bowls)
2 A big part of the community wants diversified storage for specific uses/aesthetics, like barrels
dining tables, wardrobes, grain sacks, to name a few highly upvoted reddit threads.


a compilation of the reddit threads about the issue is here https://onehouronelife.com/forums/viewtopic.php?id=6082

**Comment by cloudiirain** [comment]
To follow up on the “counter” idea, the current soil/bucket logic is completely nonintuitive for beginners. It makes no sense that you can’t use a bowl of a pile of compost (or an almost empty bucket on a well), and every day I see beginners struggling over this before they figure out this weird quirk of the game.

To make the game controls more intuitive, piles of stuff (e.g soil, water) should be counted by their smallest unit. For instance, a full pile of composted soil should be 21 units, not 7 units (x3 baskets). This way, you would be able to use a bowl on a pile of compost and decrement the counter by one. Using a basket decrements the pile by three. The client is responsible for figuring out the sprite to display based on the counter.

**Comment by TwistedHBG** [comment]
I think what would work well would be to have items for dedicated storage, similar to seed bowls. Instead of storing several items of the same type in a tile turn them into a new bulk item. Imagine making a burlap sack that you can 'turn' into a carrot sack, or an onion sack, or any other fruit/vegetable - just like seed bowls or water buckets. The same thing would work with jars if you wanted to store stuff like salt or oil.

I might be mistaken but it seems to me like the code for something like this is already implemented, the only thing you'd have to do would be creating the sack/jar item and then hooking up the transitions.

**Comment by TwistedHBG** [comment]
I had another suggestion that would go very well with new storage options, while at the same time making buildings more important. Copy paste from my forum post:

> As many people said the problem with buildings right now is that they're just not worth it. They look cool, sure, but they often make your town worse as you lose valuable tiles. We need buildings to have an another use besides temperature improvement, as that is such a small bonus it's not really worth it.
> 
> In real life we build buildings for many reasons. Privacy is one of those reasons, but what about barns and shacks and the like? We do not need privacy in those buildings, which means we build them for some other reason. We build them to protect the things inside it from outside influences.
> 
> What if buildings in OHOL did exactly that, or something similar at least since there is no weather. What if items decayed at 50% the normal rate while they are inside the building? Slow fires would last eight minutes instead of four, clothing decay would slow down while the wearer is indoors, the forge is on for longer giving us more time to smith, dyes simmer for longer giving us more time to dye clothes.
> 
> The cool thing about this idea (IMO) is that it would also affect some things negatively as some decay timers are actually good. If you have a hot steel crucible you want to take it outside as it will take longer for it to cool off indoors. You don't want to wall off your crops as they'll take longer to grow. Cows in barns will take longer to get to the milk stage, but you'll also have more time to milk them. You want sheep out in the open as you'll have to wait less for wool that way.

**Comment by trevorhackman** [comment]
Bowl of X storage is very inconsistent, there's already other issues about it. 
ALL bowled things being large instead of some large and some uncontainable would be an improvement to consistency and to storage. 

Half of the storage problem is clutter. Improve clutter and storage will be easier. In any town that does manage to get pretty old, there's so much garbage everywhere that it's hard to do anything. Anything that is permanent and undestroyable like paper accumulates and causes clutter. Mouflon hides, sheep skin, straw hat, and reed skirt should eventually decay or they turn into unremovable garbage once the town gets better clothing. Animals like sheep shouldn't infinitely spawn lambs that die and fill up the pen with dead lambs. There's a lot of things that could be improved, and there's other issues about clutter.

**Comment by jasonrohrer** [comment]
The problem with item specific containers (using the seed bowl model for everything) is a huge content creation load, and the need to make new specific containers every time something new is added to the game.

So, instead of having a "sack of carrots" and a "sack of peppers," which I could do, I have a generic basket that can hold 3 items, be they carrots, pepper, or whatever else.  Then I make the basket one time, and as long as a new item is containable, it goes in.

For reference, there are currently 679 different containable objects in the game.  SIX HUNDRED AND SEVENTY NINE.  I'm not going to make special-purpose containers for all of them.

That said, I do see how a box full of baskets is a tedious way to store 12 small items (they are two layers deep, so a pain to get to individually).

So probably just a "slot box" that can hold 12 small items directly is the most straight-forward solution here.


What I'm really looking for here is a list of problems, and things that don't make sense.

Oh, seed bowls (none of them) are not containable.

**Comment by Don-Holm** [comment]
@jasonrohrer Special-purpose containers are only for the main products, which are Eggs/Meats/wheat/dung/Milk/liquid latex/carrots. And let's forget about seeds if they are such a pain, lets just focus on those main products that are produced, that takes a lot of space and they are un-able to stack.

**Comment by jasonrohrer** [comment]
Related commit:

2a7714e1ebcbb7fa2c5cca37c6769f8868c0769f

**Comment by Booklat1** [comment]
"What I'm really looking for here is a list of problems, and things that don't make sense."


But that's not what WE are looking for. If people say barrels for raw foods are needed why not try adding it? No one has asked for all items to be contained this way, half these posts are about food and the rest also about specific stuff like all-clothing storage.

Storage isnt really broken and your commit already helped a lot but we do want storage based content. If we didnt reddit wouldnt have a lot of posts about it.

**Comment by trevorhackman** [comment]
Related 
#299  
https://github.com/jasonrohrer/OneLife/issues/292
#269 
#252 
#229 
#218 
#217 
#103

**Comment by jasonrohrer** [comment]
also related:

86cb6988e8de97cb315330989f9144c94554828f

2dbb7de93e4a6c475c8cbe61e0d701e69b221504

**Comment by Don-Holm** [comment]
@jasonrohrer I'm loving those commits! Jason grant us one last wish for today and make milkweed gives directly a thread, rather than a stalk! This is an issue that nothing else than that could solve it.

**Comment by cloudiirain** [comment]
Thanks for the commits!

Regarding the specialized containers, if it’s too much work in content creation, I think most people would be happy if a lot more things are stackable like carrots/soil is stackable.

Things that people would love to see stacked:
- Grain (make a pile like soil)
- Tomatoes
- Raw meat
- Corn
- Sharp Stones
- Bone needles
- Eggs
- Cactus Fruit
- Beans
- Corn
- Bananas
- .......

Frankly I think lots of people would be happy if a majority of items were stackable, unless there’s a clear reason why they shouldn’t be.

**Comment by laccy** [comment]
maybe make 3 piles of grain a basket of grin then store it as a pile of grain?
technically the most used item, as peope do a lot of mutton pies, so stacking mutton and grains would be nice
also the slot boxes wont contain grain bowls or clothes, i guess cause they not small
didn't try tools yet

for vanity and rp reasons a wardrobe for clothes and table for foods would be nice

not fully related but foods should decay over time with one warning, then maybe the decayed food could be used as compost material
so if no one eats those 1000 year old pies they decay, i guess pies arent the issue other than people without jobs lose interest, but al those tomatoes and peppers and such is just annoying to see hours and hours

**Comment by Spodnie** [comment]
Horse-Drawn Tire Cart can store 8 large items.
Maybe it would be nice if we could upgrade wooden boxes to have 6 or 8 slots too, and wooden slot boxes to have 15 or 20 slots.
Cost of upgrading shouldn't be too cheap, I wouldn't mind if upgrading a wooden box to 6 slots costed 2 iron and a rope and then to 8 slots another 2 iron and a rope... Or something else, up to you.

**Comment by Spodnie** [comment]
We also spend lots of bowls to store treshed wheat.
Would be nice if buckets could store up to 4 or 5 bowls of treshed wheat.

**Comment by miskas9** [comment]
Portable Sacks, that could contain Sugar, Wheat, Palm oil Kernels, Corn kernels

**Comment by Sir-Caio** [comment]
I imagine more things like the dung and scrap boxes, dedicated containers for a specific type of item such as grain silos that store 10 buckets of wheat/corn/palm kernels, tool racks that hold six tools, wardrobes for clothes and so on. It would help astronomically with organization as well as make rooms/towns overall more visually pleasing.

**Comment by jasonrohrer** [comment]
Going to close this for now, because a lot of progress has been made in this area.
