### ISSUE TITLE
cistern should allow bowls or pouches used on it

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#35]
first of all the main reason for deep wells with buckets was to feel like an upgrade, people did multiple wells instead of one upgraded well, the side effect of having wells in pond locations, was that terraforming became less viable
buckets opened up new style and now we can farm anywhere, and cistern got hit by it indirectly

the only use is to bring water from afar and store it in a cistern so kids don't need to go too far for water
it would be a nice game mechanic to allow bowls or at least pouches on cisterns
a lot of good designs would be possible 5x5 with cistern in middle, cistern in the bakery
currently we need to dig a bush out, place wooden floor, before people plant it back
a lot of times people take a bucket out of the well, take it to the left, bring back a bowl of it 1 tile to the original well
now this could be fixed with free tiles which doesn't let building/planting over them, boards tiles doesn't let planting on them or cisterns allowing bowls on them - the number of water is fixed on them, so wouldn't be an issue like with wells refilling 
the ability to place them anywhere makes it a nice late game tech, but to make it viable, should allow bowls too, if it would allow pouches only, would be enough, would be a good reason to have some pouches
this would make it equal to shallow wells
maybe decrease the storage limit, even 20-30 water would be ok initially, maybe for less stones
maybe upgraded cisterns could hold more water and have bigger storage, different graphic

**Comment by jasonrohrer** [comment]
Well, the problem is that the cistern can either store BOWLS of water or BUCKETS of water.  It can't do both.  The engine only supports one unit.  So, for example, you couldn't put in 10 bowls of water and then later take out one bucket.  The cistern isn't actually tracking water at all.  It's tracking "uses," just like a berry bush.  So it has 10 uses.  Those uses currently each allow a bucket to be taken out.

The cistern could go back to storing bowls of water.  But then you'd need to bring a bucket over and hand-transfer 10 bowls into the cistern.

The idea, for your suggested design, would be to leave a bucket near the cistern for this purpose.  I know it takes up an extra tile.
