### ISSUE TITLE
Kerosene Wick Burner on Oil Rig

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#355]
The wick burner cant be used on the oil rig, should be placable and removable to be able to use either kerosene or charcoal.

**Comment by jasonrohrer** [comment]
This is intentional, because I don't want you making a closed loop out of oil to get oil.  So you still need wood and charcoal production as part of your oil pipeline.

(This is also true for the fractional distiller, which is needed to make oil useful.  Anyway, the idea is you need two charcoal for each tank of usable kero)
