### ISSUE TITLE
Everyone has a straight face when there is a murder

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#356]
This video is a good example : https://youtu.be/cAYdtRkFFIw?t=82

The whole town gets murdered but everyone is smilling or as a straight face.

Yes there is the murder scream but there is still something lacking to make it feel like it's more serious.

When a murder is happenning i always get the impression nobody cares or take it too seriously, maybe it's because of their facial expression, maybe because only the victim screams or maybe something else i dont know.

**Comment by jasonrohrer** [comment]
There's some humor value here for sure.

Standing there smiling like an idiot with an arrow in your chest.

Emotes are under player control, so... I'm inclined to leave it that way.  If you want to angry face or whatever after you (or your fam) gets attacked, then do it.

Murdermouth is a different matter, because it's part of the "hear them coming" mechanic, which is pretty crucial.
