### ISSUE TITLE
mosquito deadly 99% times when wearing clothes pt.2

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#359]
In the previous post you answered: 

"This isn't a bug, exactly. You have yellow fever, and you're wearing a full suit of fur clothing. Being sick is supposed to require help to survive, at least some of the time."

https://github.com/jasonrohrer/OneLife/issues/266

So if you're naked you dont need help when you're sick but if you have clothes then you need help?

That's the logic?

This doesn't make sense, imo you should be able to survive from yellow fever if nobody helps you but only barely, meaning if you are well fed and go right away out of the jungle or desert.

Not depending if you have clothes or not

Or being able to remove clothes when you have yellow fever.

**Comment by Tarr-OHOL** [comment]
I mostly think the goofy issue is that you can be wearing a set of pants and shoes and that ends up being fatal due to the mechanic.

Maybe it makes sense if you're fully dressed head to toe for the fever to shoot you up to maximum temperature but cruddy clothing shouldn't be lethal with yellow fever. I'm almost inclined to say it should get the snowball treatment and just be an emote that raises temperature as the main reasons mosquitoes exist (minus punishing zoom users) was to balance perfect temperature in the jungle and unlimited bananas.

**Comment by jasonrohrer** [comment]
Yes, it would be possible for the yellow fever to NOT make you drop what you are holding, and NOT immobilize your hands.

However, the point is not necessarily to balance the jungle, but also provide a unique/interesting collaborative experience.  If you run back to town and say HELP in yellow letters, and then some people come over and feed you until you're well, and as a grown man, you F for food during that time to help them not waste food.... that's a great dynamic, and the core of what this game is about.

Unfortunate side-effect is that you're screwed if you're alone and get sick.  But that's kindof the point, right?

Mobilizing your hands would allow you to nurse yourself, which would undercut the HELP ME experience.  No one would ever need to ask for help.

Regarding clothing, it might be cool if someone who was helping you could undress you when you were sick.  They currently can't undress you ever (so they can't steal your clothes).  However, maybe when you are sick, there should be an exception.

This doesn't help if you are alone in the jungle.... but, you know... who goes alone into the jungle?

**Comment by jasonrohrer** [comment]
Turns out that letting others remove your clothes is a pretty big code change.

And yes, when naked, it's totally possible to survive yellow fever by just stepping out of the jungle.  This actually does make some thematic sense.  You're au naturelle, right?  Do as the natives do.  A westerner dressed to the nines doesn't stand a chance.

I was going to say... the problem might be that the fever isn't high enough, and everyone should die, whether naked or not, without feeding help.  But stripping down as a precaution before doing jungle work is interesting.  I also do like the feeling of needing to avoid jungles when traveling in clothes.

So, I'm going to leave it for now.
