### ISSUE TITLE
Can't undo knitting needles

### ISSUE THREAD

**Issue by FeignedSanity** [jasonrohrer/OneLifeData7#367]
Nothing can be done to undo knitting needles. You can turn all the skewers into knitting needles and nothing can be done about it.

**Comment by jasonrohrer** [comment]
This is a tough one logically.

They look shorter.  The idea is that you snap the skewers down to size when you make them, like taking a shaft and making a short shaft.  You can't get a short shaft back.

Should be some way to dispose of them.  They can't be kindling, because that would be cheap kindling.

**Comment by jasonrohrer** [comment]
Well, I guess it is 2 skewers, so kindling is fine.

**Comment by FeignedSanity** [comment]
But why would you need two? If you're snapping it, couldn't you just snap one in half? Are you breaking them both in half and just throwing the other halves away? I always thought they were just two skewers put together; I never thought about any snapping involved.

This might open up a "don't-do-that" where people are using early skewers for kindling instead of tilling. Could be viable early game grief. I guess time will tell.
