### ISSUE TITLE
Elder removal receipt with pencil stucks on the ground

### ISSUE THREAD

**Issue by MilkweedOHOL** [jasonrohrer/OneLifeData7#435]
https://edge.onetech.info/3127-Elder-Removal-Receipt-with-charcaol-offScreenSound
Elders can set receipt and pencil down without taking them apart.
If the elder did it, no one cannot pick them up but elders.

**Comment by laccy** [comment]
not fully related but: elder timer is way too short, I was able to put remove notice only on like 6-8 tiles since I need to explain to others, I guess I shouldn't let it last second to make pencil and find someone to help but it's not something I'm actively thinking about all game long that I will be 55 and I need to remove this fence, it's quite hard juggling all those papers.
