### ISSUE TITLE
Witness the dark door magic!

### ISSUE THREAD

**Issue by KilianOHOL** [jasonrohrer/OneLifeData7#567]
There is some issue with the auto-orientation of walls. The problem is that the open doors do not count as wall-elements regarding auto-orientation

![door-magic](https://user-images.githubusercontent.com/48244226/71939147-0f5e4f00-31b2-11ea-902c-9fbeabc882a8.gif)

**Comment by jasonrohrer** [comment]
Noting that this is also broken for the locked versions of doors, but I don't think the locking code will work well with auto-orientation, because auto-orientation auto-changes objects, and I worry that the lock will be changed to the wrong lock type....  So I'm going to leave that part broken for now.
