### ISSUE TITLE
Auto orientation problems

### ISSUE THREAD

**Issue by Tipy1802** [jasonrohrer/OneLifeData7#571]
I have always hated auto orientation. I always found OHOL's building mechanics to be simple to understand but with a lot of potential and now it's all gone. There used to be a fair share of architectural styles and now they are gone. All buildings look the same. It's rather hard for newbies to get their heads around it and worse of all whenever someone places a property fences or just some other walling around it changes the prebuild building's walls to corners which is ugly. The solution is really simple: Just make it so whenever you place walls in non oriental stakes it doesn't auto orientate the wall. This way we still have the option of making buildings the way we want them and  for those who think spending a milisecond on clicking on stakes is too much of a hassle  they can just use auto oriental stakes

**Comment by jasonrohrer** [comment]
Before auto-orient, the vast majority of walls and fences in the game were mismatched and broken-looking.

This wasn't on purpose, it was just due to player neglect (or more charitably, out of players not understanding how the stakes worked).

Yes, there were some "creative" uses of mismatched walls here and there, which I was worried about throwing under the bus.

But it was more than just a visual issue.  Mismatched walls left "gaps" that weren't really there.  You couldn't walk through these gaps, even though it looked like you might be able to.  And air didn't leak through these gaps either.

Corner walls are there to "fill the gaps" so that the function of the wall is clear.  If you build a fence up to a house, a corner wall will appear to "fill the gap" so that it's clear that the fence connects to the house.  Otherwise, it looks like you can walk through the gap.

See this image, and the false "gap" that looks big enough to walk through.  It's too confusing to leave in the game.

![screen00493](https://user-images.githubusercontent.com/12563681/72098897-4af13a00-32d4-11ea-808a-08ead647a93e.png)

Finally, in terms of implementation, it's not the stakes that auto-orient, but the walls themselves, which is necessary so that walls can connect to each other as a structure is completed.  So it's impractical to have two different types of stakes, which would mean that we would need to have two different types of each kind of wall (auto-orienting and fixed).  That's a ton of duplicated content.
