### ISSUE TITLE
Bottle of sulfur lacking

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#576]
Same with sand, sulfur could use an easier way to get transported. Having a bottle of sulfur would be consistent with how other powders currently work.

**Comment by TwistedHBG** [comment]
+1, I was surprised to see sulfur was not actually bottleable.

Some other bowl items that might make sense being bottleable:

Niter Solution
Saltpeter
Palm Kernels
Crushed Palm Kernels
Glasswort Ashes
Iron Filings
Turkey Broth (is this too weird?)

**Comment by TwistedHBG** [comment]
Just adding onto this as it loosely related, but after playing around with bottles I feel like 4 capacity is kind of on the low side, especially considering items like slot boxes and buckets have 10 capacity.

**Comment by jasonrohrer** [comment]
Well... it's too late now on the capacity.... there's a lot of them bottles!

Also, for wine, I drew 4 sprites, so that's where that came from.

I could have more uses than sprites, which would mean that some uses have no sprite change.

However, the number of uses is currently spread on all the different bottles, making it a real bear to change.

Probably sticking with 4 for now.

**Comment by jasonrohrer** [comment]
Also, the logic about what is bottled is generally based on stuff that might be made in bulk and stored, as opposed to something used as one step in a process.

But yeah, for palm kernels, there's the transport issue of course.

**Comment by MaDc0wUSP** [comment]
Forgot rust in a bottle too!

**Comment by jasonrohrer** [comment]
Whoops.... bear death fix has nothing to do with this, linked to wrong repo.
