### ISSUE TITLE
Table storage inconsistency

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#581]
For a feast table you can put a plate full of bread, a cooked turkey and a pumpkin pie on a table, but when trying to store it without making a feast table you can’t. This feels inconsistent.

Storage needs to work differently for tables compared to other containers. For example: it would make sense to store a plate full of bread to be on a table, while it wouldn’t make sense for that same plate of bread to be put directly into a box or cart.

**Comment by Wizadroid** [comment]
Maybe these certain food items could be classified as their own category? A medium perhaps? Then just set it so a table can hold three small, medium, or large items or any combination. But keep it so boxes can't hold medium objects. Because it seems that all food items that go on plates, and in some bowls can't be placed on tables.
Included:
Omelet
Plate of Burritos
Plate of Tacos (Both Pork and Bean)
Carved Turkey on a Plate
Turkey Slice on a Plate
Mango Slices
French Fries on Plate (Yet a bowl of Ketchup is containable?)
Buttered Toast on Plate
Bowl of Tortilla Chips (Yet a bowl of Salsa is containable??)
Bowl of Whole Milk
Bowl of Skim Milk
Bowl of Turkey Broth

But then other foods of the same size are containable on the table like Pies, Sauerkraut, Stew and Carnitas.

**Comment by jasonrohrer** [comment]
This has been fixed!
