### ISSUE TITLE
Follower & Leader Badges/Icons Disappear From No Clothes and Are Not Very Noticeable

### ISSUE THREAD

**Issue by Davidj361** [jasonrohrer/OneLifeData7#586]
I managed to get followers, but I noticed the badge would disappear because of having no shirt/clothes. Also, the badges are too small and not noticeable to see. Is it possible we can have them be much more noticeable? (Especially for exiling)

Screenshots:

![](https://i.imgur.com/rZgAUue.jpg)
![](https://i.imgur.com/ArxMjUh.png)

**Comment by TwistedHBG** [comment]
You're using a 3rd party mod that zooms out the game, that's why the badges seem so small. They're decently sized and very clear when playing the default, unmodded game. I think it would make more sense to ask the mod developer for an option to make the badges bigger.

As far as the shirt thing goes I think that is by design. If you don't want your rank to be visible at a glance you can take off your shirt. The exiled marker is visible at all times because you don't want the exiled person to be able to hide their status.

**Comment by jasonrohrer** [comment]
Well, also, you can't stitch a badge on your bare skin.

The black X mark could be made on bare skin, though.
