### ISSUE TITLE
Can't remove shaft from unused tools. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#598]
Pickaxes are notorious for being made due to being the last item on the smithing list and some fool always sticks them onto shafts thinking they're helping. The only way to fix this is to currently bust the pickax which is a real waste. 

Suggesting any unused tool be allowed to have the head removed via destroying the shaft with an axe or hatchet.

**Comment by sigmen4020** [comment]
When doing this it should probably give you kindling as well as the tool head, to make it less griefable.

**Comment by Dodg-e** [comment]
or smithing could cycle back to axe after the pickaxe

**Comment by jasonrohrer** [comment]
I was going to make shafts removable from a bunch of tools, but that opens up the exploit of taking a mostly-used tool and getting a new head out of it.  Unless I made used versions of all the heads, which is an expensive solution to this problem.

I am making the smithing process cycle back to axe after pick, though.  Not sure why it didn't do that (and I'm worried that there WAS a reason... maybe because the crafting hints don't handle loops well... we'll find out).
