### ISSUE TITLE
No door on east west tracks

### ISSUE THREAD

**Issue by Tipy1802** [jasonrohrer/OneLifeData7#610]
![Screenshot (782)](https://user-images.githubusercontent.com/49914292/73122233-36c36300-3f8b-11ea-91a6-cb44d36d0c4f.png)
No door on east west tracks

**Comment by jasonrohrer** [comment]
There are a few reasons for this.

First, I wanted to avoid additional combinatorial explosion with this extra case.

Second, I thought it would be somewhat hard to see what's going on when the cart passes through a vertical door.


But putting those wo reasons aside, I just investigated, and it turns out that the open vertical door overlaps with the track in a very unpleasing way (it ends up either over or under the track).

I'm going to leave this be for now, for all three reasons.

With crossing tracks and curving tracks, it is possible to have multiple tracks leaving the same building via the horizontal walls.
