### ISSUE TITLE
Grapes aren't edible

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#621]
I know they aren't the typical grapes which are meant to be eaten as is, but when people are starving I doubt they'd be too picky about eating them?

**Comment by jasonrohrer** [comment]
Yeah, wine grapes can be eaten in a pinch!

**Comment by jasonrohrer** [comment]
The problem is actually a food balancing issue.

Grapes don't require compost for repeat production.  Thus, they would become a very cheap food source.

However, you do get some food value from the resulting wine.

Anyway, I'll give them a food value of 1, because they're not really "good eating grapes."
