### ISSUE TITLE
Minor naming quirk

### ISSUE THREAD

**Issue by Sir-Caio** [jasonrohrer/OneLifeData7#622]
Copper and zinc ores have their actual mineral names, malachite and calamine, while iron ore doesn't (hematite).

**Comment by jasonrohrer** [comment]
Yeah... I think I'm alright with this.

I think that in common parlance, "Iron Ore" is called such because it's so common and widely used.  Plus, there are several different forms of it, and also because it doesn't have other widespread uses.

The other ones are distinct, useful minerals in their own right, beyond their use as an ore.  Calamine lotion being one example, malachite jewelry being another.
