### ISSUE TITLE
Springy doors too easy to remove by accident

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLifeData7#640]
Consider 2-person removal pattern, or some way to confirm removal.

**Comment by MonsWTF** [comment]
I am of the opinion that we can mimic the double-authentication that rails use. 

Person A still uses the knife, but they only 'begin' to loosen the door. Knife is force-held for the 2-3 seconds that the door is loose as well.

Person B now has to use a chisel to completely pry the springy door free.

This shouldn't impact North-South Rail Springy Doors, because those require the Rail to be removed before the door.

**Comment by Dodg-e** [comment]
not just springy ones every door.

**Comment by jasonrohrer** [comment]
Actually, I think the problem might simply be that it's a common tool that you carry for other reasons.

Wouldn't be as bad if it was a less-common tool.


I don't see the problem as griefing here, because it's not too hard to rebuild one door if someone takes it off on purpose.

If someone walks down a whole track, removing the whole thing, that's a huge pain to repair.

But you don't want to remove doors via mis-clicks.

**Comment by jasonrohrer** [comment]
Yeah, so I switched this to Adze.

Before, it was any fine cutter, including knife and flint chip.

I'm leaving Pine doors alone (still removed with fine cutter), because they don't require steel to make, so shouldn't require steel to remove either.
