### ISSUE TITLE
Wet Sapling pattern category into Maple Tree transition

### ISSUE THREAD

**Issue by ryanb** [jasonrohrer/OneLifeData7#66]
I'm working on improving onetech pattern categories, and I think there is an issue with pattern `categories/1806.txt`. It treats all wet saplings like maple saplings, which causes `transitions/-1_1806.txt` to apply to them. This transitions any sapling into a maple tree.

However each wet sapling also has its own transition which I assume overrides the pattern transition in the game. For example `transitions/-1_1873.txt` which changes a wet mango sapling into a mango tree.

I'm uncertain how to work around this without breaking other pattern category transitions (such as dead puppies decaying). Is there an issue with this pattern category?

**Comment by jasonrohrer** [comment]
Yes, the transitions generated by patterns can always be overridden by explicitly define transitions.

What's happening here is that wet saplings are part of the pattern (the tree-growing process) up to a point.  But then they each need to turn into a unique tree.

I could make the adult trees themselves part of the pattern, but I was worried about strange side-effects there (because trees are involved in so many other things).  There would also be a potential loop there (the cuttings are part of the pattern, and they are taken from adult trees), and I'm not sure if the code can handle that.

So, I decided to stop the "pattern chain" at the wet saplings.  They are effectively an end-point of the chain of pattern-based transitions.

And as an end-point, that would mean that all wet saplings would grow into maple trees (because Maple Tree isn't part of the pattern).

However, the explicitly-defined transitions for each type overrides this behavior.
