### ISSUE TITLE
Paint is awfully inefficient

### ISSUE THREAD

**Issue by Sir-Caio** [jasonrohrer/OneLifeData7#676]
Paint buckets are quite expensive (especially the ones that require pigments from especialty biomes) and on top of that you can only paint a single wall, you're better of just consuming the milk and leaving your walls white. For that I'd suggest a paintbrush tool or simply more uses for the paint bucket on multiple walls.

**Comment by Spodnie** [comment]
Milk is very cheap and there is plenty of limestone to make plaster, so it's not really that expensive.
But if one bucket could paint 2 walls it would be fine too.

**Comment by sigmen4020** [comment]
Biggest expense is blue and red pigment, which can only be made from rare materials (lapiz lazuli and cinnabar. Maybe one bowl of red and blue pigment could have multiple uses to make up for this?

But in terms of the other pigments (yellow and black) and the other materials (milk and limestone), I think it's probably fine enough as is. Since milk, yellow pigment and black pigment are easily reproducable, and limestone is really easy to get your hands on.

**Comment by jasonrohrer** [comment]
It's good for some colors to be rare/expensive, and others to be common.

If you see an entirely blue house, you've seen something very special indeed.

As far as making paint itself cheaper...  I'm not sure I should do that either.  The idea is that colored walls are a rare luxury.... and some colors are even more rare and special.
