### ISSUE TITLE
Can't move grown-up and old dogs that gets in the way

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#688]
Dogs sometimes get in the way in the kitchen or the smithy and it would be nice to be able to move them on demand instead of depending on AI pathfinding and chance. Both grown-up dog and the old dogs that are about to die should be moveable. Including pregnant variations for the same reason.

I would like the ability to rope a dog just like we can rope sheep, pigs and livestock, but without the speed penalty since tamed dogs enjoy walks in a leash.

Imagine wanting to confine your dog into your house, but then also take it on walks, or maybe the missus gets angry with it and orders you to abandon it in the woods or take it to another owner, or maybe you want to take your old friend to a nice place where it can die in peace.

RP opportunities as well as a fix for dogs that are in the way of your working stations.

**Comment by jasonrohrer** [comment]
The problem here is the implementation headache of all those roped dog animations.

I made to many dogs, and updating them all to have a roped version is going to be very tedious.

I'm going to add a way for you to "call" a dog, that makes it come right to you (and run faster, and further when coming to you).
