### ISSUE TITLE
After the iron hotfix

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#696]
So, We started a new town. We made ready well site. We unlocked 2 iron veins in west of it (and 0 in east). I took 8 iron from these veins, and started making tools. I almost finished making shovel and someone near made a well before us, so our well site got dry. We found out there is natural spring 80 tiles north, so we moved there. We already had shovel so we made a well there right away.
And what happened is: these 2 iron veins from the first well site respawned their 4 irons (bug), so we got another 8 free iron and we still can use and upgrade these veins (they are not muddy), but we have no iron veins straight west and east to our current well, so I'm not sure if future generations will find our veins from previous well site location.

I don't know what the best solution for this would be. Maybe making a well shouldn't require using a shovel? Shovel race was an issue even before the family mine update, it's not my first time when we had pretty nice beginning town, but someone else made a well first so all our work was lost and had to move somewhere else.

Also making another wells shouldn't refresh these 4 hunger free irons from iron veins.

**Comment by laccy** [comment]
another issue I heard, Silverstein family had no iron on their own, I guess because there were no badlands anywhere near the spring location.

Before Eves settle, it should say how many iron veins they get making that well or even block it when there is none, or they supposed to look for possible iron mines and make the well based on that which is quite unintuitive.

**Comment by jasonrohrer** [comment]
Yes, OP, that is a problem.

The reason that digging a well to the north unlocked the old veins was that the old veins were still in the radius-160 square from your final well location.  In fact, the other town digging a well first probably further unlocked YOUR veins along with theirs.

This is a pretty rare occurrence, and rather interesting.... I don't see an obvious solution.

The problem is that there were already 2x veins unlocked (for the two nearby towns), and if we let you unlock more veins to the north, there will be 3x veins unlocked by only 2 families.

And yes, if you settle in a place with absolutely no iron on your ley line (very rare), then you are screwed.

**Comment by laccy** [comment]
I mean giving one vein to each family in closest badlands would fix it

it would be nice to have a chance for a random value of +100% or anywhere in between. 

the other could be a smaller grid for iron but one vein would cancel out any other vein in that direction
this would mean that families could have 2 most cases, they would need to be really unlucky to have none
and ofc the iron could be halved, more consistency less high roll

in-game it's interesting, there is a badland generally, but the ice or jungle or desert on middle cancels out both of possible mines and it's just a few tiles difference.
