### ISSUE TITLE
Scrapping Engine will only be used for griefing

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#700]
Removing an engine from a well requires one person, no tool, and no hungry work. Someone can simply walk into a town, take the engine, and scrap it, and since scrapping it causes a net loss of two iron you can't even easily make a new one. Maybe it should required to 1) Use an adze to do it, 2) Require a ludicrous amount of hungry work, or 3) Require a certain number of adults in the area to agree to removing the engine like killing does.

Just my two cents on the issue.

**Comment by TwistedHBG** [comment]
The Diesel Engine should NOT be scrappable IMO.

The Diesel Engine is the most complex item in the game, with only a small percentage of players actually knowing how to make one.

There is always a use for a Diesel Engine - you can instert it into a well to get more water, and they're the only way to create brand new mines.

The only situation where you would want to actually scrap the Diesel Engine is if you're trying to grief a village.

Being able to scrap it is highly abusable and it can ruin hours of work and hundreds of resources in a split second (you only get 16 iron back, and also keep in mind just starting the newcomen engines requires dozens of units of water and charcoal)

**Comment by jasonrohrer** [comment]
Wait, is there more than 16 in the engine?  I didn't count myself, but that's what OneTech told me.

If there's more iron in there, I will make the scrap box bigger.

Also, this was in response to a request to be able to recycle the iron in then engine.

If you get an extra engine from an abandoned village, what are you going to do with it?  The iron is stuck in it.

Yeah, you can create a new mine.... so they are useful for out-posting only, right?  If you don't want to outpost, the extra iron is wasted.

Anyway, for griefing, the engine can currently be stolen.  Stolen seems worse than scrapped to me.

Protect your valuable things should be the answer.

**Comment by jasonrohrer** [comment]
But please do let me know how much iron is in the engine!

**Comment by TwistedHBG** [comment]
Onetech says it requires 16, but it also says it requries a Pulley Drive Mechanism which by itself costs 2. So 18 in total - https://onetech.info/2365-Diesel-Engine/recipe

I feel like scrapped is much worse than stolen - first of all, if stolen the engine will at least remain in one piece and it can be retrieved and reused, and all the effort that went into it is not really wasted. Second of all, scrapping an engine appears to be easier than stealing it. If a potential evildoer wants to scrap it they just bring a box next to a well and toss the engine in in under a second, and bam, massive damage. When they attempt to steal the engine there is at least a chance for the town to catch them and retrieve it.

**Comment by DiscardedSlinky** [comment]
People are going to remove an engine from a well and scrap it before anyone can react to it. This is a TERRIBLE idea. Unless you make it like a 5 person job to scrap it this is going to end very poorly.

**Comment by jasonrohrer** [comment]
Yes, I see that it is 18, will fix that.

So... what if they steel it and hide it?  Then the engine AND iron is gone forever.

They do need to make a "scrap box" first, not just any box, which is admittedly not very hard.

We could have a waiting period before scrapping an engine, where you set it in there and wait X minutes for the engine to "settle" in there (a checkmark appears on the box), implying consensus, then you can whack with hammer.


BUT... my gut tells me that you already have a method for ensuring consensus (property fences).  I know you don't want to use them.

But by insisting that I fix all valuable and vulnerable things in the game by making them inherently invulnerable (and thus cutting off a potentially legit use of those things, because it's too powerful and dangerous), you're insisting on a world where you don't NEED property fences.


The engine can be stolen or scrapped from your mine or your well.  That means you should protect it and limit access to trusted parties.


People are already keeping cisterns around... why not fence the well, let a few people run it (a few people are running it currently anyway, b/c of kero know-how), and then bring the water out to the cisterns?

I think the REAL problem is that towns are not planned around this, so there are floors and other things in the way already, but those things can be removed to make room for a fence around the town's most valuable and necessary possession.

If you're not using property fences for THAT, then what on earth would you ever use them for?

**Comment by TwistedHBG** [comment]
If someone steals and it hides it is is only gone until people find it, not forever.

Property fences are only useful for sheep pens or walling off your own private area for something. You can't use property fences for protection because you only live for 60 minutes at a time. There's no way to know what the person you give access to will do, so might as well cut off the middle man and not use property fences at all. You get the same end result, except you remove the annoyance of using property fences for blocking stuff.

Also, it's not about fixing valuable and vulnerable things here - this is the exact opposite. This is about adding a new interaction that can (almost) only be used for damaging a town.

**Comment by jasonrohrer** [comment]
We can imagine situations, given that iron is scarce and precious, that someone would want to recycle an engine.  That is a powerful thing to be able to do, when necessary.

Property fences are inheritable, as you know.

The fact that "you don't know what the next generation will do" is the entire point of this game.

You're supposed to not "throw up your hands" in the face of that uncertainty.  You're supposed to be conducting trans-generational planning, through communication between generations, and passing traditions along.  Actually doing that is where stuff gets real... where the "well master" isn't just role-playing, but is actually the guy in charge of the well, and he will pick an apprentice before he dies, to carry on the tradition.

If you're not doing that currently, it's because you don't need to currently---OR because you're ignoring that need, at the expense of your village's survival.

Adding more things to the game that makes such trans-generation communication necessary is a good thing.


I'm well aware that many players HATE the idea of trans-generational cooperation and communication.
