### ISSUE TITLE
Inconsistency : Killing pig is not hungry work

### ISSUE THREAD

**Issue by Elsayal** [jasonrohrer/OneLifeData7#703]
I didn't saw the reason for it. Maybe it should be hungry work too, since the carnitas are so good.

Anyway, thanks for this amazing game :)

**Comment by laccy** [comment]
honestly is quite hard to organize people to do it, even if it's not hungry work

right now pigs are at 660% compared to berries while most top foods are 250%
I guess a bit of nerf wouldn't hurt, but it's quite hard to get a piglet, kill the boar, quite dangerous
the cornfield helps with the cows too so it's a quite good middle ground to cows

but the issue is:
pigs need a lot of space to cook effectively
they also need a lot of bowls
they still look way too similar to sheep meat, a colour change would be nice
still seeing a lot of pig meat in bakery and every time you take it out people bring it back
