### ISSUE TITLE
Photos can't be seen by players

### ISSUE THREAD

**Issue by Elsayal** [jasonrohrer/OneLifeData7#704]
Making in-game photos is a bit complex, but photos can't be seen if you don't go on the main site of the game. But how many players go there and then click on the "photo" link ? Maybe only people who makes the photos, and it's a bit sad.

I suggest that the last photo can be accessible in-game or at least from the game menu (like genetics score). Someone suggest on the forum that photos should be put on a wall. If it's possible, it would be amazing.

Whatever you choose, thanks for this great game :)

**Comment by jasonrohrer** [comment]
If you are in the photos yourself, an icon will show in your family tree listing, so that's another way to discover them.

I'm a solo programmer, and I need to pick my battles.

The web-based implementation of the Photos feature was the quickest path forward, and it works, so I need to leave it alone.
