### ISSUE TITLE
Removing domestic gooseberry bushes is a hungry work work.

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#716]
Newbies/griefers plant too many gooseberry bushes in towns and it's hard to stop them from doing it. Removing them is also hard because it's a hungry work job.
I get it why removing wild gooseberries was made hungry work for in the rift, but I don't think it's still necessary.
Please make it that removing domestic gooseberry bushes isn't hungry work anymore.

**Comment by laccy** [comment]
the whole point of removing the bush is saving the water
already loses on the initial cost of tilling the soil, but that can't be undone

there are 2 situations here:
-a griefer removing the bushes to starve others
-a veteran arranging the city

for a griefer won't matter tool usage, and hungry work even helps to archive his goal, since he can eat more berry, remove bushes and prepare other bushes for removal by losing pips.

the original water removal was bad since you lose 17-20 worth of pips using water vs not having the next refill on the bush. but the timer was actually smart.
just need to swap the water for another item. the mallet would make sense since you need to make floors anyway if you doing it for redesigning purpose. the time limit is the same for fence removal, and either takes 2 people or one veteran who can quickly swap items. who is smart enough to be that fast, generally smart enough to do it for a reason.
adze would be another option but that could lead to accidental flooring removal if someone picks up the mallet in the meantime since swapping would be same as adze removal right-click.

**Comment by Spodnie** [comment]
I think using shovel on staked gooseberry bush is enough.

Btw, griefers don't remove berry bushes, not worth it since they can be replanted very easily, also they usually don't want to be caught and get cursed, they would definatelly be caught in an attempt of removing whole gooseberry farm.

In some towns there are about 50 berry bushes and there is no way to rearrange it if removing every single bush is hungry work, so please, remove hungry work from this action.

**Comment by miskas9** [comment]
I think the bigger deterrent is the water usage because all those people that want to order and rearrange staff do it for efficiency as well, and water usage is counterproductive to this efficiency.

**Comment by jasonrohrer** [comment]
The main reason was that dug domestic and dug wild produce the same result, so they're both hungry work.

But wild no longer grow back, so there's no reason to slow down the digging of those.
