### ISSUE TITLE
Another bad biome dropsy abuse. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#720]
Whenever you stand in the middle of a bad biome on a floor you can drop items into the bad biome by filling the good tiles with items. 

Step 1. Have expert make road/flooring/whatever
Step 2. Ride horse or take cart with tiny road leading into bad biome.
Step 3. Fill tiles with whatever to block items to be dropped on road.
Step 4. Walk into bad biome which then forces you to drop it into the bad biome.

Found someone who had done this exact set up in game to dump stuff into a desert.

**Comment by Tarr-OHOL** [comment]
Also to note you can dump stuff in bad biomes by running over snakes on horses (which has also been done in the past.) 

All these issues with dropsy makes me think it would be better for recipes to be tied to family homelands rather than having a mechanic which is constantly abused for the sole sake of being annoying.

**Comment by jasonrohrer** [comment]
There's no ready fix for the horse-snake one, because where should that stuff be dropped?  You're in the middle of the desert already.

The road one also is pretty much impossible to fix.  Where SHOULD the stuff go?  There's no room left.

For the other ones, I really wanted to fix bugs that could be triggered by accident.

For this, if someone really wants to drop stuff this way, well.... let them?

Finding an expert family is supposed to be a core part of the game.  If there's something really great dropped in the desert, find the desert family to help you retrieve it.

Now, there might STILL be problems finding desert families (too far away, etc.), but that's game-breaking for other reasons, even if there were no specialists.  Because if other towns are too far away to interact with.... that's just boring and uninteresting.
