### ISSUE TITLE
Some food almost never get made

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#728]
Here's an example of foods that were almost never eaten yesterday (from main website food stats):
![image](https://user-images.githubusercontent.com/51952537/79156065-82d7b400-7dd2-11ea-8ae8-a96cefc3480f.png)

This is a sign that this kinda food need to be more rewarding to make, by for example increasing their pip value or bites.

Other foods I would include on this list:
Icecream
Wine
Baked Potato

**Comment by cordy-123** [comment]
Can we get a slightly different sprite for COOKED french fries?

When you mouse over french fries, they are always disappointingly RAW. So over time, you don't even check if they are raw or not. Coz they're always raw. 

Raw Fries
![](https://onetech.info/static/sprites/obj_2872.png)

Fried French Fries
![](https://onetech.info/static/sprites/obj_2892.png)

**Comment by sigmen4020** [comment]
Good point, might also be one of the reasons they aren’t eaten frequently.

**Comment by Wizadroid** [comment]
These are also somewhat biome locked foods tho? French fries and tortillas can't be made without palm oil, and ketchup and salsa require tomatoes, and in the case of salsa peppers all from the jungle. 

In the case of wine that is locked behind tires ie newcomen tech, and they also provide next to nothing because grapes aren't part of the compost requiring crops. Hence why grapes also provide so little. Let's also not forget that they require glass which only black families can do, and isn't really worth is for a food that provides 1 pip.

Ice cream is locked to gingers because of the snow, and also require cream which can be quite annoying to make in bulk or at all since skim milk really just sucks.

I guess most of these are so sparsely made because people don't know how, and if a player that does know how logs in, they have a 1/4 chance of being the right race to make it cause it seems very unlikely that most towns have the things required for these foods.

I have no reasoning for baked potatoes. Baked potatoes are lit.

**Comment by sigmen4020** [comment]
Even more of a reason these foods should be buffed. If you have to go through the race restrictions to get them they should at least be worth making. And judging by the numbers they clearly aren’t. Case in point; this is how much pumpkin pies were eaten on the same day. (Another food locked by race restrictions but gets eaten a lot more than the other food)

**Comment by jasonrohrer** [comment]
There is a complete overhaul of food values incoming.
