### ISSUE TITLE
Property Fence Slot Box is missing.

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#741]
you cant make a slot box when the box is on property fence.

**Comment by jasonrohrer** [comment]
This is true!

Unfortunately, there's kindof a combinatorial explosion...  there are already 12 different versions of these boxes (for different fence orientations AND different states of decay of the fence).

Just adding slot versions would double this...

But being able to add slots in place is two steps (cut plus add thread), so that means we'd get a double explosion, resulting in 3x objects (36) along with all the transitions.

You know, if a partially-made fence slot box decays.

I know this is an inconsistency, but I do need to pick my battles.  People can use baskets to pass stuff through.
