### ISSUE TITLE
knife can mush meat bowl but cant mush carrot berries bowl

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#750]
It is weird that we can use knife for a mutton bowl but we can't use it for a carrot bowl.

**Comment by Spodnie** [comment]
Would be cool if we could mash all types of things that can go into raw pie crusts, since we use knife often in the kitchen anyways.
Idk about the realism tho, but if you decide to do it, here is the full list of things that cannot be mashed with a knife:
https://onetech.info/547-Bowl-of-Carrot
https://onetech.info/258-Bowl-of-Gooseberries-and-Carrot
https://onetech.info/256-Bowl-of-Gooseberries-And-Rabbit
https://onetech.info/262-Bowl-of-Rabbit-and-Carrot
https://onetech.info/257-Bowl-of-Gooseberries-Rabbit-and-Carrot

**Comment by Spodnie** [comment]
I mean, I'm actually fine with mashing things with a sharp stone, I don't mind if it stays like it is now.
