### ISSUE TITLE
Digging graves breaks the shovel too easily.

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#757]
Burying the bodies in a town shouldn’t be seen as wasteful. But with how quick graveyards can break shovels it’s a wasteful activity. Grave digging shouldn’t be punishing the town, but rather help them by cleaning up the corpses. Considering that some actions like shoveling potatoes and poop doesn’t take up shovel charges, it doesn’t seem fair that another action (grave digging) with no particular benefit breaks one of the towns most important tools.

**Comment by Spodnie** [comment]
Yeah, I'm also mad at people burying bodies, especially if they do that too close to the town, blocking useful space.

But it's realistic that digging a big hole for a body wastes a shovel use, while it wouldn't be realistic to break a shovel only because picking a dung with it.

**Comment by jasonrohrer** [comment]
What does currently break a shovel?

Looks like pretty much only digging up one-off things (like cacti, spent sand pits, or whatever)

Oh, and actually shovelling the dung into a compost pile.  So yeah, some part of dung management breaks the shovel.  The idea there is that one step wears it, instead of ever step (moving dung shouldn't wear it, but turning it into the pile should).

The potatoes are a special case.... and it's really kinda backwards.  I'm not too happy about it.

**Comment by jasonrohrer** [comment]
I'm going to fix potatoes to wear the shovel, and then we can figure out how to rebalance their food later.

**Comment by miskas9** [comment]
Please make them wear the shovel only 1 use 
( the first potato  wears it but the next dont ? could work?)

**Comment by Spodnie** [comment]
Oww... See what you did sigmen? :D
Damn, potatoes not worth making anymore I guess. Maybe if they give 2 yum (+half potato) it would be worth it.

**Comment by sigmen4020** [comment]
Yeah rip.

Guess Jason is ok with grave digging being a wasteful activity that doesn’t help towns in any way, so I’ll stop posting about it.
