### ISSUE TITLE
scraping engine

### ISSUE THREAD

**Issue by MRGold777** [jasonrohrer/OneLifeData7#772]
I have had this idea for some time now and I have seen lots of engines being scrapped it really has no reason other then griefing I have had the idea of making it so that instead of scrapping why not be able to take it off of  abandoned wells so it has a use again so a family can use it, and settle there and not have to get kerosene to be able to own the well. most of the time you don't need to take it off so it would be great to be able to take it off when a family dies or aka abandoned wells thank you for your time -Mr.Gold

**Comment by Spodnie** [comment]
Engines from wells and iron veins should be irremovable. Yeah, some families have only 1 iron vein and couldn't afford making another engine for their vein, but they can get iron from other families. It would be funnier than constant fight against engine griefers.

It's not realistic either, wells wouldn't need to be fenced off irl to protect it from their family members.

**Comment by Tarr-OHOL** [comment]
Jason will tell you to use fences. 

The people going to destroy something are going to weasel their way into doing it anyways. The whole game has to be balanced around the people griefing because Jason finds in interesting that it takes two seconds to ruin an engine and ten minutes to remove a stick in the dirt.

**Comment by jasonrohrer** [comment]
Meanwhile, if you find an engine in an abandoned town, the iron is stuck in it forever, if the engine is stuck in a well or a mine, and can't be removed.  If it can be removed but not scrapped, it will just be hidden by a griefer.

You can't champion for freedom and lack of restrictions on one hand and then beg for restrictions on the other.  Is freedom good or bad?  Should players be powerful or powerless?

You want to have the power to unilaterally murder (Tarr), but you don't want to have the power to move the engine from a mineshaft to a well outpost or car or plane?


The fences are "restrictions" that are placed in the hands of the players.  You want your engine (or any other item in the game) to be scrap-proof or hide-proof.... well, you have the means.

Or I could go through the entire tech tree, one by one, locking things off at player request.

**Comment by Spodnie** [comment]
Let them be scrapped, just make the irremovable from wells...

**Comment by Tarr-OHOL** [comment]
The issue here is this is a recipe currently ONLY used for griefing. 

No one is using this recipe to start up an outpost (you can't do this because of homelands and kerosene costs)

Almost no one what so ever is doing this to mine iron while at the same time people are mass destroying engines because the recipe is too damn simple. 


Most of these towns that require a diesel engine to revive are towns that had their engine stolen or destroyed. Even adding something simple as an elder note reduces the griefing potential of working with an engine without "ruining" the outpost or mining idea. 


The point is the ability to destroy an engine isn't terrible but the implementation is. Why is removing knee high sticks harder than an engine? Shouldn't the town be deciding whether or not to short out their water supply for iron? 

Sticking an elder note on a diesel engine to remove it or at least requiring one to recycle it fixes all the issues but instead we're sitting here remaking the same complaint because no one wants to use crappy fences.

**Comment by cordy-123** [comment]
Another idea:
Removal of an engine from the well requires a community vote.

Someone should say:
"Should we remove the well engine?" (Should be a specific phrase)

Requires 5 people within 10-20 (?) tiles of the well to say:
"YES!"

Every "NO!" requires an increase in the amount of "YES!" by 1.

---

Could also use slash command:

/REMOVE WELL ENGINE VOTE
--> starts the process and has a whistle effect but with a "V" instead of "W"

People answer with:
/YES OR /NO

Requires you to be 5 (?) years old to vote.

---

Only the family who owns the well can vote to remove it.

If it is an abandoned diesel well, requires at least 3 people to vote.

**Comment by miskas9** [comment]
instead of a vote, A pose system would work better. you have to shit click the engine and other people join you.
