### ISSUE TITLE
QoL - More stack functionality

### ISSUE THREAD

**Issue by Sir-Caio** [jasonrohrer/OneLifeData7#774]
Stacks are great but working with them can still be kinda wonky. Some simple functionality could help reduce the amount of "clicking" required when using stacks/piles, such as:

-Using an axe on any choppable wood pile = kindling pile (and takes more durability than normal out of the axe, if that's possible)
-Using a flint chip/knife/sharp stone on a pile of corn ears turns it into a pile of shucked corn
-Any bowl that could accept a carrot (empty, gooseberry, rabbit) + any carrot pile = add a carrot to it
-Empty clay bowl + dried corn pile = bowl with corn cob
-Clay plate + shrimp, mango, onion and tomato pile = add to the plate
-Skewer + pile of arctic char = skewered fish
-And a lot more with alum, electrum, lapis/cinnabar and niter piles

**Comment by cordy-123** [comment]
Can we stack raw rubber tires?

Sometimes you just need the buckets! 

Yes, you could place them 1 per tile. But that takes up a lot of tiles in a small bakery.

**Comment by Spodnie** [comment]
I think it's similar as picking berries one by one to fill a bowl. It just feels more realistic, and that's good I guess.

**Comment by jasonrohrer** [comment]
For the tools that get "used up," like axes, there is a limitation where it can't work on another thing with uses, like a pile.

The transition engine only supports tracking ONE "uses" item, not two in parallel.

Otherwise, there's a huge combinatorial explosion.  Each use of the axe acting on each use of the pile, etc.

But yeah... there's also something nice about manually chopping each log or whatever.  That's what work feels like.

You get a small taste of automation with the table when rolling dough... that's not too realistic, I guess.

But I also do plan on adding higher-tech stuff in the future that can process some things in bulk (think of a log splitting machine).


But I will do the other things listed here.

**Comment by jasonrohrer** [comment]
Raw tires (like raw tortillas) are very sticky, and can't be stacked.

**Comment by jasonrohrer** [comment]
Whoops... didn't mean to close this just yet.

**Comment by jasonrohrer** [comment]
Alum is dropped into a liquid.  A little weird to scoop it up off the ground or a pile with a bowl of liquid.

**Comment by jasonrohrer** [comment]
And finally, nitre, like alum, is dropped into a liquid solution, so it can't be scooped up.
