### ISSUE TITLE
Player numbers dont scale with the production

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#778]
Iron and water seem to be a fixed amount while players got iron and water upkeep. This means, the more players, the worse the ratio. Which could be an endgame problem with a really huge population, but not an early middle game problem.

This means cities do not need more people and does not benefit from having them. With the new mining system, iron is limited for Eves and the first city of the family (or second if the first has none but that also implies that they can die out faster).

There needs to be something that benefits from having more players, resources that scale better with population or activities that profit from having more players.

Such as unlocking techs, like each unique player has to contribute to something or occasional resource drops/respawns based on population.

Even the population could be limited by certain technological levels or food in an area to provide a better spawn system for the players.

A quest system could be also considered where people would need to fulfil time-based tasks for a reward.

**Comment by Nika50501** [comment]
Having higher player count CAN increase production but you need a good amount of collaboration to achieve it, which is kinda difficult/impossible but that's the point of the game. 
First, mass producing items decreases the amount of "intermediate" goods needed and increases your efficiency greatly. For example you use the same amount of palm oil whether you decide to make one french fry or a hundred. Same goes with forging and kindle, paper and water, pies and kindle (the only two examples where intermediate goods I could think of were palm oil and kindle). So producing goods for five players doesn't take too much more effort than producing goods for twenty if you specialize.
Second, because of YUM you need many different food types. Producing every single one on your own is impossible so you are forced to divide up and produce different foods for each other. More players could mean more food types and a thriving civilization (yum bonus is really good if you get 19-22 food types). Assuming people use around 330 food in a lifetime, making three sister stew in late stage and feeding it to every person requires 0.24 iron and 12 bowls of water [and 9 soil]. In comparison having 26 yum foods and eating one of each can get you below 0.1 iron and 7 bowls of water per person* (you could probably go lower, I just kinda got lazy and made a rough estimate, you can see some of the food values at the bottom, I didn't calculate soil values but a similar decrease can be expected)
Thirdly, if you get truly huge civilizations you are allowed you split up into smaller sections that are quite far away from one another (say 10k blocks) use transmitters to communicate and use planes** to get your tar spot scouts as far from the main camp as possible (if i understand correctly there is no limit on oil rigs except distance right?). Having multiple people working on scouting while equipped with transmitters would allow them to go out much much further. 
These are all too idealistic but to happen but it is definitely possible to scale production if you collaborate, but for that you'll kinda need to talk to people (which is why we should have the standard in-game chatting system that we so desperately need instead of the ohol version).

*Here are some of the values, but keep in mind that less soil is used for a lot of these as well.
                                                                           iron                         water
corn                                                                  0.0049                     0.25 
popcorn                                                           0.00082                   
milk and skim milk in different containers(6)  0.00294                   0.15
one gooseberry in bowl and one gooseberry 0                             0.28571
grape                                                               0.00198                  0.2
wine                                                                 0.00083                  0.0833
...
sauerkraut, french fry, french fry with ketchup, bread, bread with butter, one bite of each of the eight pies, icecream is very efficient if you can produce it too
..

**Planes use up too much kero and are bound to get griefed/lost

**Comment by laccy** [comment]
that's simply not true because food producing needs only 2 tools
oven or hot coals, sometimes flat rock on it which is the same

more populations mean more munchers, which means that your production is more likely to stop due to mass starvation
people can do multiple foods in the same life, they not really doing it due to issues with communication, but you get  more excess with less people so they can make different foods while having special ones in stock

you can calculate soil as 0.25 water and 2 tilings. that's the composted soil value roughly.

still not the point, you get roughly the same amount of trees, the same amount of rabbits, soil, water, iron per family, which scales worse with more people. there is too much focus on the resources, no much on the work. people got upkeep, more than 12 people can't even really do different jobs or use different tools. even composting costs you water and iron so you run out faster than with fewer people.

**Comment by Nika50501** [comment]
What I meant was that specializing work will sometimes lead to work getting done more efficiently. For example, when I tried forging alone I could usually make 3 rough iron made from each forge, when I forged with one other person we made about 9 from each forge. I'm sure if I worked with two other people I would be able to do 14-17, but wouldn't really benefit from more than two people. But that's literally the only example where that happens and even then having more than three people is excessive.
You are definitely right about stockpiling. Having 3-6 players each just creating excess food one food type at a time would be much easier to maintain that having 12 people doing it. Going beyond 6 people in a civ is pretty much pointless. Especially since you get so many munchers and griefers when you scale up a population.

**Comment by jasonrohrer** [comment]
More people does bring division of labor, which leads to some efficiency gains, assuming that switching tasks has a cost, or assuming that you can become more efficient at a task with practice.

But yeah, the resources mostly do NOT scale magically with population size, and that is intentional.

However, there is some scaling that you're not considering, which is that once the server population gets big enough, we start having multiple villages (created by multiple Eves), and they can each unlock more iron.  This isn't based on population, but number of families, which does tend to scale along with population.

Also, a bigger population can keep a water outpost going, which means more water.

But in general, stuff is supposed to run out over time, regardless of population (it would indeed run out faster if the population was larger).
