### ISSUE TITLE
Specialty biomes.

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#779]
Moving around a big desert or another specialty biome only because we are carrying a cart  or any other item is annoying. I mean, we can walk in all biomes anyways, so why can't we hold items there?

What if we could enter any specialty biome while holding items, but we couldn't drop it in there and couldn't pick anything from there (unless it's our specialty biome)?

I think this change could make the game feel much nicer.

Some griefers would die in specialty biomes a bit more often to drop items in there, but it's still possible with horses, so it's not a big deal I guess, and it doesn't happen too often as far as I know, Griefers prefer to hide things far away from everyone instead of dying.

Yellow fever would need to be changed: If jungle is not your specialty biome, you wouldn't drop items while being sick until you leave the biome, after leaving you would drop it right away. Hopefully it would be easy to programm.

**Comment by jasonrohrer** [comment]
This is one of the big benefits to horses or other vehicles... you can ride straight through with cargo.

I think the problem with NOT dropping when entering a bad biome is clarity of messaging.

Being sick or hurt in the game makes you drop what you are holding, which makes you take notice of that state change.

If you could carry whatever into a bad biome, you'd get sick (sneeze or whatever), but you might not notice.

Then you'd go to try to DO something in that bad biome, like chop a tree with the held axe, and it just wouldn't work.  Or let's say you're hungry in there.  You try to set down your basket to eat cactus fruit or bananas, and the basket is stuck in your hand?

The messaging at that point would not be clear.  Something that looks like it should work doesn't work.

The messaging upon entering is VERY clear, and then you know why you can't chop the tree (because you're not even holding an axe, of course).  You can't try to set down a basket, because you're not holding a basket.  And your character can't grab anything, because their hands are clearly in the "sick position" (empty hands held against stomach instead of normal walking animation for arms).

Yes, this clarity is violated somewhat when riding a horse or car, but in that case, the only action mysteriously blocked is dismount.  "I can't get off my horse in here, hmmm."

But at that point, if someone is advanced enough to be riding a horse, they have probably experienced what happens at biome boundaries otherwise, and they've been exposed to the more clear messaging.
