### ISSUE TITLE
Dyed Clothes

### ISSUE THREAD

**Issue by cydlee** [jasonrohrer/OneLifeData7#786]
Undyed cloaks, long dresses, and skirts can be made into other articles of clothing (i.e. needle and thread + undyed cloak = undyed long dress), but not the dyed variants. Please add transitions to remove the inconsistency between dyed clothing and undyed clothing.

**Comment by jasonrohrer** [comment]
I got partway implementing this, but then I realized there was an unavoidable combinatoric explosion.  There are a bunch of different clothes (and more coming in the future, probably), and a bunch of colors (and more coming in the future).  I could potentially stick the sewing steps into a pattern, but even when I try to do that, I'm stuck with the dying sound (sploosh sploosh) on blue skirt creation (for example).

Thus, there's a pretty good reason why clothes in the game are "garment dyed," because it makes the whole underlying implementation so much simpler and easier to maintain going forward.
