### ISSUE TITLE
Use chance applies to water refill

### ISSUE THREAD

**Issue by ryanb** [jasonrohrer/OneLifeData7#79]
From what I can tell in the code, the use chance applies to pond/well refill transitions. So a pond will only apply the +1 transition 20% of the time. This would give an average of 1 water every hour instead of 5 per hour as [intended by this commit message](https://github.com/jasonrohrer/OneLifeData7/commit/d7ea4908009b814c34947a2f714bd0fad8ade1f8). This means it is better to drain a pond completely so you get 1 water every 30 minutes.

If this is the case, shallow wells only have a 6% chance to refill every 3 hours, but a dry well has 100% chance to refill in 30 minutes.

Is this correct?

Update: this is a duplicate of [this issue](https://github.com/jasonrohrer/OneLife/issues/154). Feel free to delete.

**Comment by jasonrohrer** [comment]
Okay, fixed this so that all seepage-based water sources produce 1 unit of water per hour, both in the first step, and on average for the subsequent steps, which are probabilistic.  And by 1 unit, I mean one bowl, not one bucket.  This means that the deep well produces water very slowly, if you're counting buckets.

So, the advantage of the upgrade is in a temporary increase of reserves, not a greater production rate.  To get beyond the pond rate, one needs to build the pump.
