### ISSUE TITLE
[Unreleased] Making a Hitching Post shouldn't use up the rope

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLifeData7#794]
In an ideal world dissasembling the hitching post would give you a rope back, but since hitching posts are created every time a horse is hitched onto a fence this would create an easy way to create infinite ropes.

Creating hitching posts with rope can easily be used to permanently destroy all nearby ropes. It would be great if it worked similar to the pine walls, where the rope is required to make the item but isn't used up.

One other thing to consider is it might make sense to use a lasso instead of a rope. Ropes are often used to manage animals and mislicking on the fence is highly likely. Lassos are the main horse tool, and using lassos to make horse hitching posts would make sense (provided the lassos are not used up when making one).

**Comment by jasonrohrer** [comment]
I was worried that people would make hitching posts everywhere.... but they can do that anyway with the horse (by hitching it everywhere).

Oh, because hitching post converts other fences to horizontal, I was worried that people would run around making them everywhere, just to make things ugly, if they were completely free....  though I guess it's easy to fix with the shears.

**Comment by TwistedHBG** [comment]
Perhaps hitching posts could decay back into fences after some time, 10, 20 minutes? Making a new one is is fairly simple (especially if it doesn't use up resources) so it decaying doesn't really matter much.
