### ISSUE TITLE
Can't put on table

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#795]
[Sliced Pumpkin Pie](https://onetech.info/3370-Sliced-Pumpkin-Pie) and [Carved Turkey on Plate](https://onetech.info/2187-Carved-Turkey-on-Plate) can't be put on tables.

I just made 2 tables in our small kitchen, because we had many pumpkin pies lying on the floor, but I couldn't put them on those tables.

**Comment by laccy** [comment]
yeah they should be able to be contained, I made the mistake to carry the sugar near it then I was a manual task to bring all across the city, inconsistent with other pies

**Comment by jasonrohrer** [comment]
The pumpkin pie is intentional, because you need to put a whole one on the table as the first step to making the feast.  If you could also contain it on the table, there would be confusion about your intentions.

Will fixed the carved turkey on plate (that's okay to put on table, because it doesn't start a feast table).

**Comment by Spodnie** [comment]
Would be more intuitive if we could put sliced pumpkin pies on tables.
I mean - a whole one on empty table would start the feast table, in any other case (not empty table, not whole pie) we could just put it on the table.
It would be useful, please.
