### ISSUE TITLE
Fences in general, why they don't worth it

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLifeData7#796]
You wanted to make fences viable but it's still missing something

When it worked: in the rift I made small fortresses
<img src="https://i.imgur.com/Np8QWHf.png" alt="text">
<img src="https://i.imgur.com/0fKfUo4.png" alt="text">
<img src="https://i.imgur.com/yTQCiE3.png" alt="text">
<img src="https://i.imgur.com/ZZlBDyy.png" alt="text">

This was protecting from attackers and gave a fresh start to organize, but the main advantage was a new water well 40 away, it wasn't too far to move some resources and allowed me to make a decent setup, eventually, it decayed or was extended, when the setup was bad, towns got scavenged and ruined, when the setup was good, they were taken over

3rd picture you see a fence I made, it saved a small black family and gave them a chance against the raiders, 4th picture you see the same fence the next day, it was cramped but was still going
I didn't count for nursery and the graveyard, storage space
I would say around 18 tall and 30ish wide was a decent setup

Nowadays I tried similar things but there are a lot of problems with it:
-in the rift, I could go back there and continue the work on it, it still needs players to go back and keep it up but it's harder now to do so, you didn't like this mechanic I guess
- even tho I can make it faster than real walls, it won't last, eventually, the animals get out, decays and disappears, I found more valuable to make a smaller setup which is lasting the years than to make something temporary bigger in size
- there are no renewable resources inside, then it worth nothing, the main value in the rift was the water inside it, and the well in 40 tiles distance, since we got wells much further, no iron for outposts, there is no good reason to make fences nearby towns, it won't be useful and it will require a lot of time just to make the initial cistern(s), compost, move animals there, etc. 
-graves: fence towns become massive graveyards, sometimes more than 25% of the space occupied by graves which really makes them ugly and unfunctional
-players still against others who hoard, even if you don't, like making your own tools and share the products of the fence, they still more likely to curse or kill you for stupid made-up reasons
-takes too much time to get in and out, I remember when feral eves roamed, the fence protected out food, but when we had no food inside, getting out took longer and one daughter starved by trying to do so
-it's not safe, it only takes one person to leave a gate open and the whole thing is compromised
-impossible to fence up existing farms like berries or corn, no space, and even if you do, they will plant new, also requires extra tools if people go in separate locations
-it's ugly looking
-some kid always fixes them when not needed and before you tell them, it will be fixed, removing them with notes is a very slow process

the good parts:
-fence boxes decay to boxes, which saves time, it's a wall until you can afford boards and ropes
-animals are kind of a renewable resource, so containing them in a fence is viable
-if somehow you can make a fence line outside or inside the future wall, it keeps animals there and gives you time to make those walls later, you can start exploiting a resource before making costly upgrades

I would like to see compartments within towns, farms that  are placed by function, not generic 3x3 farms where you carry the soil and water around then carry the products around
the leaders could give compartments to take care of but right now they are more of a problem than a solution

<img src="https://i.imgur.com/RQFL7hA.png" alt="text">
made a small sprite change to files, these are fences, rotated butt logs 90 degrees then added them on shafts, thinned them out for gates, made it a bit more enjoyable when it looked decent

Possible solutions:
-ability to upgrade fences instead of waiting to remove them, permanent structures would look better and people would use them, could be used as scaffolding. like fence boxes decay to fences, fence walls could be upgraded with stone or adobe, then I wouldn't be awkward to build inside them. Ability to convert fence walls into gates/locked doors somehow.
-fences could be between tiles if the engine could do that. this would also allow upgrading in some way
-removal of a full line should be possible, not tile by tile, this would need marking corners only then removing would remove everything between corners, should be a size limit so people won't lock up towns
-maybe standardized sizes, only rectangles or squares available
-defining inside and outside, if you own a gate and you are inside, the ability to reorganize or remove parts quicker, maybe fence walls belong to the closest gate and destroying gate that side would remove all fences up to the corners
-auto closing gates for better access control. maybe different modes for gates like buying a ticket to enter to allow shops or services.
-shop front and vending machines: selling or exchanging items for other items, serving people and distributing food. Fence tables, for example, would be tables upon fences like boxes but with some more functionality.
-more renewable resources, I could imagine clay or flat rock mine, limestone mine, a fence could be a requirement to make one of those, and it could provide some income of clay or flat rock or limestone, making pottery, road making or taco, adobe or plaster walls available trough time and allowing a family to specialize in something, and inherit it through generations, these actions are mainly cosmetical, and while making food people don't have too much time to gather from far away
-some sort of fast travel and transport trough higher techs, horses are quite rare, bicycles or rickshaws or something could replace them at a higher cost of iron
-a need for private space or items. if players would have something to protect and not share, like a bed that provides them bonuses, even if they would make one for others they would protect their own. even if it's cosmetical it would be decent, but probably would need a logical bonus to them. Some sort of resource generation over time that has to be collected by the same person. Maybe towns would need a bed for each person to extend their population, they couldn't go over more than 2 homeless persons. these could act as home markers and track people and population. Beds would show who are they assigned to (track if they are alive) and if clicked show their location by an arrow. This would limit the population in low tech towns.

This is a long shot but: upgrade fences to some sort of palisade walls, allow destroying them slowly and gradually (hp or durability system). They could act as a small fort/castle/panic room, allow different activities inside like building an arena for skill-based fights. They could protect a flag or something and families collecting flags could receive an advantage. 
Trading post inside fences: order food or other resources for a price (other resources or a new currency) it would arrive automatically on donkeys. A fort would have a requirement of size, several tech upgrades and would provide a way to fight between families.

**Comment by Arcurus** [comment]
yea fences currently are not that useful these days except for as outlined above for an early sheep pen and some engine protection.

**Would suggest the following improvements:**
give a third state to gates: open / close and auto
auto opens and close it automatically like the spring doors do, but only open automatically for all owners. this would make them lot more easy to use.

**To the decay problem, why not make it like in screeps?**
There walls can be upgraded, the more effort you put in the more strong they are. same effort needs then to put in to pull them down. Implementation wise they would need only an counter for the strength. Hitting a fence / gate with a round stone would give them one strength, hitting them with a sharp stone would remove one. in both cases you would loose X food.

All additional fencing logic could be removed.

Additionally you could get an red "!" mark as warning if the fence is "attacked"


Further as said above, fences could be up gradable through walls and sheep pens.
And gates with doors.

Also walls and doors could follow the same logic and could be "strengthened" like fences.

The difference between doors / fence pen openings and gates could be that doors auto open for all allies while gates only auto open for owners.

Also fences / gates could be allowed to pass very slowly like 30 second time (you can climb over them) while doors / walls could not be passed. Of course you would drop what you have in your hand and the owner would get an red ! mark as warning.


To renewable resources, yea thats a big problem, there arnt any then animals or (little bit water?)?

To coming back to the same spot. yea currently design wise the game discourages you to go back to the same spot, which for sure is the main limitation of creating property right now, then what is the use if the chance ending up there is close to zero, if you wont hard core play for 1 hour 30 min in between and then die-cycle or spend lot time one traveling. I guess a difficult to craft reincarnation spot could help for that, but dont know if it is wanted by design.

**Comment by jasonrohrer** [comment]
This is a pretty diffuse issue.

Auto-opening gates isn't possible, because of the way auto-opening fences and doors work, they are inherently non-blocking (so you can ask for a path through them, and they open as you pass through, but they are non-blocking the whole time).  Can't make property gate non-blocking all the time for obvious reasons.  I get that they're a pain to use...

I've done a lot of work to make property more viable in the last few updates (through inheritance).

The issue of maintenance is an interesting one....  would be nice if they stayed "fresh" automatically as long as there was a live gate nearby or connected, but making it work that way is pretty difficult.
