### ISSUE TITLE
Can we turn off gain/lose genetic score for the first generations?

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#797]
As in the title.
I don't play as an Eve even if I'm born as one, I just let wolves eat me.
Lately I have been /dying in very first generation towns too.
And all that because of the genetic score. No matter how good you are, as an Eve you will always lose tons of genetic score, same will happen to very first generations people with high gene score.
Many babies have to die in super fresh towns, can't afford everyone. Many noobs who survived first 3 years also die soon after, because they are too noob, and that always happens.

What I suggest is turning off gain/lose genetic score if we are 3 or less generation. If we are at 3 generation, our kids/grandkids shouldn't affect our gene score either, even tho they can be 5 generation.

If you don't like it, it's fine, I will just keep avoiding playing as an Eve and in super fresh villages. Not big deal to me to be honest, but I think having high genetic score shouldn't discourage people from playing in low generation families.

**Comment by Arcurus** [comment]
yea, had the same problem, eve towns are lot more difficult and therefore crash your score drastically if you play in them. 

An possible solution would be to use the statistics from the server to balance out the generational difficulty for each generation. Also it could balance out the server restart difficulty or different day times.

**Comment by jasonrohrer** [comment]
Turning it off completely is a little weird, because then the family members wouldn't show up in your score sheet.

Instead, we should figure out why being Eve is so hard, and whether they are being overloaded or not.

This recent Eve had 3 kids, two which lived into adulthood, so that doesn't seem too crazy:

http://lineage.onehouronelife.com/server.php?action=character_page&id=6236588

I'm going to close this for now... if you have any insights about why early gen towns are too hard, please let me know.
