### ISSUE TITLE
/LEADER command is (almost) useless + leaders in other families

### ISSUE THREAD

**Issue by cydlee** [jasonrohrer/OneLifeData7#798]
It only shows the leader if he/she is on your screen, so if the leader is not right next to you, you have to murder-target someone to find the leader. I think an arrow pointing to the leader and the name of the leader being displayed would be much better than the current way it works. 

Also, in some cases the leader of family X will be a member of family Y, which means that nobody in family X's town can exile and kill griefers. It is hard to get people to follow you because they will think you are doing what Bobo Bill does in every one of his videos now, which is getting people to follow him so he can kill everyone. Maybe make it so that you can only follow members of your own family? (Not sure if this is the best solution.)

**Comment by Spodnie** [comment]
It's not useless, I've been using it whenever needed. But yeah, an arrow and text how far is the leader could be usefull.

**Comment by cordy-123** [comment]
problem with how far....usually jason's arrows....if it is below 1k tiles, they don't show how far....since the leader is probably in the same town....

**Comment by Arcurus** [comment]
jason mentioned, that an arrow to the leader will come.

> Also, in some cases the leader of family X will be a member of family Y, which means that nobody in family X's town can exile and kill griefers.

i thought currently for the ally count only the close ones are considered, so if a leader with lot followers in this villages exiles him it should still work. The problem could be, that all will follow by default the leader in the other family, that would be quite bad, they should instead then follow the the highest close gene score allie by default. Same would be true for the /leader sign, it should lead to a close leader if there exists one even if he is only the "sub" leader, his exile should still work.

Restricting following different families would be not a real solution, since in theory different families could split up and create their own villages, but still be allied...

**Comment by jasonrohrer** [comment]
Yes, this arrow has been added to your top leader this week when you type /LEADER.  Not released yet, but done and working.
