### ISSUE TITLE
Bobo keeps killing families.

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#804]
I was victim last life, he had a friend with him. He exiled 2 people and killed us right after exiling. There is no defence against that. Please fix it as fast as possible.

We had so many cool towns, but he just keeps killing all families, no sense trying to beat the record, which is 158 generations after the food changes, since he will just kill all families sooner or later.

I don't know what the solution could be... Hmm...
For sure we should be unable to follow other families, Why are we even able to follow people from other families? We can't live with them anyways, I see no point in this and it only makes it easier for Bobo and from what I've seen he always brings a friend from another family to help him.

Maybe some kind of voting that would kick everyone who is above us from their position? If enough people voted (majority? maybe, but not necessarily if you make us unable to follow other families, if 4 people from the same family trying voting out the leader that means something is wrong with him), then someone with highest gene score would become the new leader. Would be cool if votes of killed people still counted.

I don't know, but we really need something to stop this shit person.

Btw, it wasn't flat structure in this case, I had at least three people above me if it matters.

**Comment by jasonrohrer** [comment]
How did he become the leader?  That's the fundamental question.  Was he in your family himself?

I'm hesitant to prevent you from following someone from another fam.  What if a good fellow comes into your town from far away, and might make a good leader?

**Comment by jasonrohrer** [comment]
Like in this video:

https://www.youtube.com/watch?v=HLpcSTsp23k

This isn't straight-up griefing, but something else.... I mean, people are walking right into it.  He's holding a bow, and standing by a bloody pile of bones.  They listen to his command anyway, and play the game.

Then they have 12 seconds to get away when he targets them, but they just stand there and get shot?

**Comment by jasonrohrer** [comment]
What if you can't manually follow someone who has lower fitness than you do?

**Comment by Spodnie** [comment]
Many people follow someone when they are old age instead of letting it be done automatically, that's how he could become leader I guess.
Yeah, if we couldn't manually follow someone with lower fitness than ours I think this could work.

But still I think that being able to follow other families makes no sense. Even if a good person from another fam comes to us, we don't want to be able to follow him, he should talk with a leader if he wants to give orders, and the leader would give orders for him instead of following him.


As for not running away, I don't know why people don't do this, possibly they learned from posse update that they can't be killed. Also if a person first gets exiled, what's the point of running... Where would she run? If bobo's friend joined posse they would outrun anyone anyways, I've seen people running away and still got killed, that's why he uses a bow and not knife to kill people.
But people not running away is not an issue worth fixing in my opinion.

**Comment by TwistedHBG** [comment]
Only being able to follow certain people (and not being able to know which people you can follow from within the game) feels weird.

I don't think Bobo is that big of a problem any more. He seems to grief about three lives per week. While it is probably very annoying to be his victim, the actual number of people who are affected is fairly small.

There's a good reason why people in his videos seem indifferent - he is unable to grief people that care, so he has to keep trying until he finds a town that has an indifferent population. Most of his attempts are failures due to all the recent anti-griefing changes and those don't get uploaded to YouTube. I've been stalking his family tree and it's kind of funny how many times he gets killed at a very young age by people who see right through his nonsense.

**Comment by Spodnie** [comment]
He makes videos 3 times per week, but he kills families more often.

**Comment by TwistedHBG** [comment]
That is almost definitely not the case, you can look at his account and check his lives and every successful griefing attempt gets uploaded. There's a reason why some time ago he had a new video almost every day, and now there's 2 or 3 per week tops.

Most of his lives are either DT spawns or deaths at a young age due to unsuccessful griefing.

**Comment by jasonrohrer** [comment]
The reason you'd want to follow someone from another fam is that they might be a good leader.  If that's the case, that should be allowed.

I want to allow Heart of Darkness type scenarios...

https://www.youtube.com/watch?v=KxLFdJLSho8

**Comment by Spodnie** [comment]
Yeah, being able to follow anyone is a good design.
Being unable to defend against tyrant is an issue that I hope you will find a nice solution for this in the future if you are not going to fix in now.

/Unfollow could help in this but as long as tyrant has at least one follower, people who unfollowed are still vulnerable, and picking a new person to lead requires too much coordination, therefore Bobo will always win until you make us able to defend easier.

**Comment by Arcurus** [comment]
why not just make anybody attack able if he tried to attack some body in the last 3 minutes.
The leader would still have the advantage to decide when the fight starts , so he can prepare, but others could fight back against him if he is evil by just attacking him after he attacked / killed somebody.
