### ISSUE TITLE
Pens are messy & inconsistent breeding

### ISSUE THREAD

**Issue by voy178** [jasonrohrer/OneLifeData7#808]
I don't like to see dead baby animals. It makes me sad. :( 
Pens are often crowded with bones, dead animal babies, and the adult animals themselves. While one solution is always to make a pen larger, another (potentially) better solution would fix the inconsistency in breeding produce animals.

Out of all domesticated animals, only the goose and cow requires food to give offspring and have offspring otherwise. That leaves us with domestic mouflon, pig, sheep, bison, and boar. What if they also required to be fed to produce offspring?

Now, I don't mean that raising animals should require more food but that we should add food at a different stage and skipping the dead baby animal phase.

Any domestic adult animal (unshorn) should be feedable and will then only produce a single baby animal that will skip the hungry phase and go straight to adulthood after a while. The baby animal still retains all the benefits as if it had been fed instead of the mother animal. No resources are wasted and the pens are more manageable while not having to be much larger.

Exceptions. Wild animals should work the same as now. Domestic boar is dangerous and should maybe be excluded for safety concerns. Cow calves should work as now since you're stealing it's milk and food, while the other baby animals get fed by their mother. Dogs are fine as they are.

On the topic of manageable pens, maybe big animal bones (sheep & pig bones) could have their despawning time reduced by an hour or be made desposable in a trash pit?

**Comment by voy178** [comment]
In addition, breeding will be less tedious as you do not have to guard the baby animal for when it leaves its mother and becomes hungry.

**Comment by TwistedHBG** [comment]
I've been thinking the exact same thing recently. My thoughts on this are similar but also a bit different - advancing an animal stage should always take food, the same way cows work now.

Shorn Sheep +F> Domestic Sheep +F> Domestic Sheep with Lamb => Domestic Lamb +F> Domestic Sheep

Domestic Pig +F> Domestic Pig with Piglet => Domestic Piglet +F> Domestic Pig

Domestic Goose +F> Goose Egg => Gosling +F> Domestic Goose

+1 for better animal bone management.

Also I know this issue was recently closed, but we really need a way to kill cows.

**Comment by voy178** [comment]
I don't think that would make things interesting at all, Twisted. It would just be a pain to grow and haul all that food. I'm not about to fill more bowls with berries than the bare minimum required for husbandry, why double the busy-work?

**Comment by Spodnie** [comment]
At least we have realistically big pens and it's interesting that bigger pens are better than smaller ones. Different towns have different size pens, it's good to see really big pens sometimes, when people actually put enough work to make it properly.
With this change we would probably have 4x4 pens, maybe 5x5 because why making it bigger?
Not fun in my opinion.

Twisted, did you just suggested to feed sheep twice(first big one then small one) to get a new sheep? That would be a big nerf for whole sheep economy.
Feeding gosling again would make it really not worth it making cooked geese, since it would be just better not waste the egg and make omelettes, people don't make geese farms anyways for some reason.

I really like it like it is now, and I hope it won't change.

**Comment by TwistedHBG** [comment]
It would be a nerf, yes, and maybe it would be too much. But I do think it would make sheep herding more interesting, maybe? Perhaps fleece could be turned into a Small Ball of Yarn which could then be cut into two balls of thread to compensate? I always felt it was very weird that an entire's sheep worth of fleece gives you just a tiny ball of thread.

I agree with feeding Goslings being a bit too much, I guess it's not really needed since you create them at will by placing an egg in dung.

What if you could feed animals directly from the Bucket of Corn? That would be interesting, I think. Mashed Berries and Carrot could also be bucket-storable, and sheep could then be fed from buckets directly.

This is a bit off topic now, but I also think if animals were changed to require feeding for every stage, animal troughs would be a cool addition. Store X portions in them and animals come and eat them when they require food for the next stage (similar to how sheep eat carrots).

**Comment by jasonrohrer** [comment]
Sheep eat carrots randomly when they cross the carrot patch...

There's no support in engine for an animal to seek out a given object and head there.  The problem with implementing that would be two-fold.  First, authorship (how do we specify what an animal is seeking?), but second, the overhead of an area map search every time an animal moves.  If you have 10 sheep in a pen, each time they move, they have to check if there's a trough in range, which means checking the map database.  If we have 10 villages with 10 sheep each (extreme example), that's 100 map searches happening every few seconds.

Thus, animals could eat from troughs, but they would only do that through random happenstance, which would be frustrating.  Though I suppose that if animals don't NEED food to survive, but only to advance to the next stage, this could be okay.  You could shear them all, fill the trough, and then come back to most of them regrown by random chance later.

**Comment by jasonrohrer** [comment]
But yes, it does make sense for animals to get triggered to give birth by feeding them.  Less constant clutter.

**Comment by laccy** [comment]
trigger the lambs (and piglets) with food, but they wouldn't die, I guess it could have a middle stage to the animals, that would need some resizing and sprites but it would make sense

lambs are slaughtered a lot, especially easter time but I guess other religions eat way more lamb and chicken than Christians, since no pork. so a middle phase would be good for that too. Older sheep are kept for milk and wool but they generally killed each year cause the longer it goes the worse the meat. 

It could be some logic to it, since we got people re-feeding sheered sheep even now, wasting a lot of meat, and that kind of matters. So if the sheared medium size would be fed again, it would grow instead of just giving wool, so it would provide more fleece overall but a fixed amount. That would still be a nerf so it would be better if the sheep food would be 2 portions, or a different food could be used (sheep likes potatoes a lot). right now sheep lost the main food source status, I guess that's fine. Less meat more fleece would be better I guess, people would use up for clothes or pads or nets anyway.

Killing medium-sized sheep would only be viable if it gives some new food types and 1-2 yum but less meat.

I guess the best way would be:
3 portions of food for each berry bowl and carrot (rabbits got 3 so the pouch and the flat rocks is already usable)
feeding big sheep would grow fleece, feeding woolly would give a lamb, over time it would grow into a medium sheep
medium sheep could be sheared then fed to grow old
would take 2/3 portions to grow (fed and overfed status) and give fleece, 1 portion just for re-growing fleece if naked
I guess that would be a slight buff for fleece but overall less meat if the medium size is unkillable. also harder to grief It without feeding them first.

one nice idea was that enclosed pens could grow grass inside which would function as a pasture. When sheep goes on it, would eat and produce fleece. it's fine if it's random, overall the effect is the same, people could manipulate sheep by abusing the follow and flee mechanics to redirect them to pastures so herding would be viable (maybe animals could flee from dogs). The downside would be that preparing pastures would require multiple or bigger pens to do it effectively. I guess the engine can't detect inside and outside so maybe players would need to plant grass. Also if it's an item it would block the sheep from standing on it. 

I guess the preparation could be just mixing poop with soil, that tile would grow some grass after a while. So the poop could be recycled to feed them. since that would limit the pen, the best action would be filling a pen almost to maximum then a few sheep took inside there from another pen, when the other is empty, preparing some grass and switch back and forth, since there are no dead lambs, managing poop would be not so annoying, we don't use most of it now anyway, some value to it would be okay. Then eggs could use it up for a different scenario where you breed goose. This would give some choices where to go from there.

**Comment by Arcurus** [comment]
when sheeps now get only a lamp when fed, why not let the lamp by itself grow into a full sheep to have the same cost? Another thing is with the change, that raw mutton before was kind of gratis since it was a by product of fleece production, which was kind of nice;.

**Comment by miskas9** [comment]
https://docs.google.com/spreadsheets/d/1oO6j0lgsJoo-3gw-H6dSht9d_KqLuKADuODaDcjIDgs/edit?usp=sharing
About balance:
if you need double the feed to produce meat then, in the end game Cooked mutton is less water-efficient than berries. 
to reach higher than a cooked rabbit cooked mutton food value would need to be 13.
for the mutton pie to be little better than rabbit berry carrot pie 13 food per bite is fine as well.
(even with those food baffs in the late game, mutton foods are worse than before the change.)

Noob trap issue:
IF you shorn the sheep for wool then to reproduce it, you need 3 feed units. This is extreme punishment. 
Cows when feed produce milk and bbs
Sheep should do the same, Wool and bb.

**Comment by voy178** [comment]
I do think allowing lambs to grow up without getting fed would be the smartest choice to not gamble with the food values as they are now.

**Comment by miskas9** [comment]
yes lambs grow up without getting fed would be a solution but then he will have to change all the animals as well for consistency. 

about the current values, mutton needs a baff anyways. From 8 to 9 to be better than a cooked rabbit and worse than rabbit pie.

**Comment by Arcurus** [comment]
>Cows when feed produce milk and bbs
Sheep should do the same, Wool and bb.

that sounds great!

**Comment by Spodnie** [comment]
Can't they eat only half of the carrot/berries bowl?
Make [Bowl of Mashed Berries and Carrot](https://onetech.info/260-Bowl-of-Mashed-Berries-and-Carrot) has two uses. Feeding sheep/lamb would only use one use, while other activities with it would use two uses (there are only 4 other activities besides feeding for bowl of mashed berries and carrot). Remove the ability to feed them with not mashed bowl of berries and carrot.

Then we can leave it that shorn sheep don't make lambs but only wool.

And make domestic mouflons need to eat too before making sheep.

**Comment by jasonrohrer** [comment]
I'm going to leave the wild/dom animals alone, like mouflon or domesticated boar.  They have babies without feeding, but they do it slower.  So there's a trade-off.

I'm also going to give one extra pork and mutton per sheep and pig to balance this change.

The problem with making feeding as shorn sheep produce wool AND a lamb is that it brings back the clutter problem if you're just trying to farm a bunch of wool.
