### ISSUE TITLE
 Claiming an abandoned Exhausted Deep well is nearly impossible.

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#809]
If you find an abandoned city and you want to claim it. Even if it has a ton of resources, if it has an exhausted deep well, then it is nearly impossible to run the well and capture the city in time.

Removing and placing back a valve could trigger the exhausted deep well and claim it as a hometown.

I was an eve kid. We found a wealthy city with all the needed goods and camped there. After I had grandkids and I was getting old,  I made a well near the city to have a hometown, people didn't want to move through as they rightfully thought that the wealthy town is their home as they grew up there.

**Comment by laccy** [comment]
the making of the well and upgrading it is guaranteed. the newcommen phase has a low chance of actually being done, and the engine phase is a huge unknown, generally, you won't have an engine and if you do, they screw it up. any case it's way better to store water in that cisterns and not in the wells, but its a problem for new family claims. you might have enough food and water there but you claim it before doing the chores, but you cant guarantee continuity if you do so leaves you in a spot where you cant do anything about it.

**Comment by jasonrohrer** [comment]
What's the problem exactly?

That you can't make an engine in time to get the well running and claim the town?

Don't you have engine-making tech in the old town?


It's supposed to be hard to make an outpost like this...

**Comment by jasonrohrer** [comment]
Oh, wait, you were part of a new Eve group...

So, you were stuck re-settling a town that had no water?  And you were nowhere close to having an engine?

Sounds pretty normal...

**Comment by miskas9** [comment]
we are eve group, I spawn in an area that has big and wealthy abandoned city, Iron/food/clothes/water. 
All resources are there. 
to make the engine and kero to claim the city we need rubber, But if we visit a city all family becomes homesick and die out. 

Are we supposed to make a camp 200-120 tiles away from that abandoned city and let one female there to keep the family alive ?

**Comment by TwistedHBG** [comment]
One of the reasons this is a problem is because Eves don't spawn in the wilderness anymore, they spawn near other existing cities. They must rely on those cities because generally there are not enough resources in the wilderness to start a new camp. I was an Eve/kid of an Eve three times in the past few weeks and every time we had to take a bunch of stuff from an existing town to kickstart our own nearby well until we can build up the tech to claim the well in the existing town.

Sure, you could run in a random direction until you find actual wilderness, but a) you still need to stock up on clothes/food from an existing town because there is no wild food, b) if you want to run far into the wilderness you're going to have to let a bunch of babies starve, and c) why go through the trouble of settling in wilderness when you spawn right next to an existing city?

When it comes to claiming wells, what if you could add/remove floors to Wells, similar to how Ice Holes work? Adding/removing a floor would count as interacting with it and it would claim the well. Is that even possible?

**Comment by jasonrohrer** [comment]
Here's what I'm not understanding:

You guys want to claim a dry well, right?

Because.... as soon as you get some water from a well, that counts as claiming it.... at least it's supposed to work that way.

But what good is a dry well to you if you don't have the tech to make it wet again?  How long are you really going to survive there?


The idea is this:  if you're not getting water from there, which you need to survive, then it's not really your homeland.... yet.

**Comment by TwistedHBG** [comment]
If it's a dead town all the tech is already there, except rubber. Getting rubber is fairly trivial if you have everything else - grab a cart with some buckets and bowls and check for nearby waystones. The town often has plenty of water in cisterns already, it's just that you can't get babies in there for the time being.

What happens now is the new family just settles right next to the dead town and takes food from it until someone goes out and gets some rubber, then they can move into the town proper. I think the problem stems from the fact that new towns aren't really viable/possible any more, any new family has to live in or from old towns.

**Comment by DougLefelhocz** [comment]
> But what good is a dry well to you if you don't have the tech to make it wet again? How long are you really going to survive there?

That depends on how much food is around.  I would also assume such a place has domesticated animals, tools, kilns, and at least one oven also.

**Comment by Arcurus** [comment]
> You guys want to claim a dry well, right?
the thing is, since engine and fuel can be griefed the practice is to empty the well in cisterns. so there could be tons of water, but you cant claim since you need rubber but getting rubber makes you homesick.  Adding when you get water from cisterns for the homeland claim could work....

**Comment by Arcurus** [comment]
the eve placements could also need some fixing. why not simply calculate the average position of all players and then calculate a random close not dry natural spring to this center point for eve spawning which has no other players nearby and has some wild food. 

This would fix that eve spawn in exhausted areas with dry wells and no wild food and would also fix that eve spawn always moves from east to west and therefore gives not much time to develop a road system.

**Comment by miskas9** [comment]
What if you can put water back in well to claim it?

**Comment by jasonrohrer** [comment]
I thought the problem is the dry deep well....

Arcurus, regarding Eve placement, that kind of search could be expensive server-side.  It's cheap to find out where the players are (we know where they are already), but to find a non-dry spring would involve a potentially unbounded number of database queries.  (Depending on how far players had spread).

Cisterns as homeland anchors is a viable idea.

Then you could make an outpost buy building a cistern, and bringing water there from the old homeland.

**Comment by Arcurus** [comment]
to the Eve spawn:
The number of used server resources can be limited by letting the algorithm calculate the score of X semi random chosen possible eve locations and then choosing the best scored ones.

i outlined here a very simply algorithm which has a constant max cost. All parts are quite trivial if it is possible to query game objects close to a given position:
https://github.com/jasonrohrer/OneLife/issues/624

**Comment by laccy** [comment]
that's what I was saying like 3 times :D
good cities got cisterns, bad cities got wells with water in it
they start the tech later but they can be revived while good cities with the water already moved out to cisterns can't cause the well limitation

it's a good fix but still won't solve the issue of stolen engines, cause good cities made engines, bad cities stuck at Newcomen phase. why don't we steal newcommens and stanchion kits too? :D

For eve spawn: I was born between 4 cities as an Eve, I mapped out before so I recognized the brown town, basically, I had 4 old cities around, 3 of them turned out to be empty of any wild food and no food left behind. Meanwhile, I had kids, 5-6 girls left and right. I starved, not a single food in 200x400?  born as Eve again. I run for the 4th town. 2 guys cockblocked me out of it.

Also is these double wells intentional or a side effect of family deaths? I see well spots in 40-80 distance of dead towns.
