### ISSUE TITLE
Bug - Geese not producing eggs

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#811]
Lately I've been making goose pens, I want this way convince people that making eggs and cooked geese is simple, fast and nice way to make yum foods. People almost never were making goose pens.

https://cdn.discordapp.com/attachments/703011254666526740/713896481492566036/2020-05-24_01_20_07.png

Everything worked fine until there were this many geese in the pen. They stopped producing eggs then.
I fed them like 5 times and got only one egg. There were still a few empty tiles, but even if all tiles were occupied, it would be cool if they still produced eggs after feeding them.

Same happens with sheep dung, Sometimes sheep don't produce dung if there are nearby tiles occupied by other sheep.

**Comment by jasonrohrer** [comment]
Yes, this is not a bug...

Geese need empty tiles to stand.

You have 16 spots in that pen.

There are 10 gees in there, and 1 egg, 1 manure, and 1 bowl of eggs.  Seems like there's extra space, but if you feed a goose in a crowded area, that goose can only move by swapping places with another goose.  Thus, it can't lay an egg, because another goose needs to land there.

One solution would be to have the animal produce the manure or egg in place, and then move off of it later.  In that case, the goose would be stuck standing with the egg if there was no room to move.  Eventually, the whole pen would have eggs and geese and be grid-locked.
