### ISSUE TITLE
Do we still need gradient dry springs?

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#818]
We have expert way stones now, so maybe we don't need gradient dry springs anymore?

My reasoning is that first generation families instead of making everything from scratch just scavenge everything from abandoned towns, which are too easy to find thanks to gradient dry springs.

I do it myself, never had a problem finding an abandoned town with tons of things to scavenge thanks to gradient dry springs. I do it because it's the most efficient way, but it's like cheating and I wish it wasn't that easy to find abandoned towns.

**Comment by TwistedHBG** [comment]
If you're going to scavenge stuff from abandoned towns you're going to be able to find dead towns with or without gradient springs. Without the gradient springs it might take you a minute or two of searching, but you'll be able to find it anyways.

I don't think they're as needed as they were in the pre-waystone era, but I don't think removing them would make the game better either.

**Comment by jasonrohrer** [comment]
The problem is that if there's a dead town around, you can't use the expert waystones to find it.

And if you want to make your own well, without the gradients, you have no way to figure out which way to walk, besides trial and error, which is not interesting.

Two cases:

You're standing at a dry spring, and you want to find you way to a wet one.

You're standing at at a dry spring, and you want to find your way to the well that caused it.

Gradients help with both.

I've been meaning to add some diagonal ones for a while.  I'll do that now.

This does the opposite of what you want (makes them even more useful).

I'm really trying to eliminate as much "wandering around randomly" gameplay as possible.

**Comment by Spodnie** [comment]
Damn :P

**Comment by Arcurus** [comment]
its 50% 50% Spodnie :P
