### ISSUE TITLE
missing transition. loose Hitching Post

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLifeData7#820]
first of all, I really want Beef rather this fix. 

you can not remove a Hitching Post with a mallet and shovel, you need to transform it to a gate first.

**Comment by TwistedHBG** [comment]
You can use shears to turn it back into a normal fence.

**Comment by jasonrohrer** [comment]
I think the problem here is that every time you use a horse on a fence, it turns into a hitching post.  So it's very easy to get a lot of them.

Then, if you want to make a gate in the fence (add short shaft) or dig up the fence, there's an extra step for every tile.

So I will add these extra transitions for convenience.
