### ISSUE TITLE
Process of removing property fences with Elder Removal Receipt takes too long.

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#828]
As in the tittle. I mean, it usually can't be done in 5 minutes if we want to remove many fences at once (an animal pen for example), and that's how much time elders have.

It takes long time because we must wait a few seconds after each sign, then drop the receipt and then we can continue. If we do the mistake (elder does the first sign instead of second) then we lost about 15 seconds without any progress.

Could you make the process easier and faster, please? Ideally, if we could just sign after sign, without waiting and without the need of dropping items, please.

Suggested fix:
Add transition:
[Temporary Removal Receipt](https://onetech.info/3124-Temporary-Removal-Receipt-neverDrop) + property fence = Property Fence with Partial Notice that decays into property fence after 10 secs (a new item, just to prevent copying paper, the same as [this](https://onetech.info/3115-Property-Fence-with-Partial-Notice), but would decay into property fence instead of property fence with unsigned notice if Temporary Removal Receipt was used instead of pencil).
And
[Elder Removal Receipt](https://onetech.info/3127-Elder-Removal-Receipt-with-charcaol-offScreenSound_R) + Property Fence with Partial Notice  = Property Fence with Removal Notice

This way one person could just do signs on all fences he wants without waiting, and then an elder would just do second signs on all those fences, without the need of dropping Elder Removal Receipt to get pencil back.

 .
 .

https://cdn.discordapp.com/attachments/703011254666526740/719129532380086352/2020-06-07_10_39_46.png
We wanted to upgrade our sheep pen, but I didn't even try removing property fences, since the elder had only 4 minutes left. No chance to make it in time. We made real sheep pen above this one and people will just wait until these property fences decay. Never seen people trying to remove whole sheep pen with elder remove receipts, most likely because of how it currently works.

**Comment by miskas9** [comment]
Let the leader function as an Elder too. It easier to find the leader than an elder that knows and has time for the job. Sometimes elders aren't there as well

**Comment by jasonrohrer** [comment]
The reason this works this way is so that one elder, working alone, cannot unilaterally remove fences.

It takes a two-person team, with at least one being an elder.

One person signs the initial notice, which gets stuck in their hand for 12 seconds (preventing them from performing the second step themselves).  The second person, the elder, then has 10 seconds to perform the second step.

Note that the elder in the process is NOT slowed down at all, nor forced to wait for anything, since they can set their final receipt down right away.

So if you have several non-elders helping, they can post lots of notices, and the elder can run around and sign them all.

This seems okay to me.... property fences that someone has been caring for should be hard to remove.

I'm also not eager to pile another power onto leadership.  It's nice to have a thing or two left to the elders.
