### ISSUE TITLE
You can't contain slaked lime in a horse cart

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLifeData7#829]
When you make it in bulk (Which you have to for paint) it's extremely annoying to have to carry it around

**Comment by jasonrohrer** [comment]
I think some of this stuff has changed since this issue was posted, but no bowls of liquid can go on the horse cart.  They are all currently marked +contLabDish, which means the only container they can go in/on is the lab table.

However, pastes can go in carts, like plaster.  And the bowl of water can't go in the cart either (it is +contFoodDish, so it can only go on the table).
