### ISSUE TITLE
Babies refuse to eat

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLifeData7#839]
https://github.com/jasonrohrer/OneLifeData7/issues/746
I know it was closed, sorry for making another issue.

I had 7 kids last life (they all survived to 60) and they wasted so much of my time while growing to 3yo. I was so happy when I finally became 40yo and finally could play the game... For 20 minutes.

I get the intentions of making it that we can feed only starving babies, but it really didn't make the game more interesting for babies. I would say it did the opposite and furthermore it made the game much worse for mothers.

We put babies next to a fire anyways, much more often than we used to before this change, because we don't want to waste pips when doing things.

I'm pretty sure there is no going back to the old system where babies could always eat whenever we picked them, so I'm asking you to make it that we don't lose a pip when our baby refuses to eat.
This way I will be able to take my kids with me while I'm farming, or cooking or whatever activity in the town. It will be surely more interesting for babies, and most importantly, for me, a mother that doesn't want to waste 3 minutes of my life everytime a baby is born.

Yeah, I know about recent change that allows having only 4 living kids, but newbies often die young, and even if they didn't, 4 babies would still waste too much of my time.

**Comment by Arcurus** [comment]
> so I'm asking you to make it that we don't lose a pip when our baby refuses to eat.

i thought its like that already? You only loose a pip if the baby was hungry.

**Comment by TwistedHBG** [comment]
You always lose pips when picking up babies, no matter if they eat or not. I agree that we should only lose pips when they actually do eat.

**Comment by DiscardedSlinky** [comment]
I agree with this. I like to carry my child around with me as I work and it means picking them up and putting them down a lot. If a town is low on food though I usually just hold them for the entire 3 mins and wait it out. It's boring and takes forever and it makes me dislike my children even though it's not their fault.

**Comment by Arcurus** [comment]
agree, it would encourage more to bring the baby along.

**Comment by jasonrohrer** [comment]
The problem with only losing a pip when they actually eat (the game NEVER worked this way, by the way) is that then you can "spam feed" a baby with no consequences.

The goal (and I know we're really far away from that still) is to create a sort of "dance" between mother and child, where communication between them really matters, and there's no way to "brute force" the feeding to make communication unnecessary.

Before this change, people still lost a pip on every pick-up, whether or not the baby needed food or not.  The difference, before, was that you'd almost always feed them something, because if you let 10 or so seconds go by, they'd probably need at least 1 food.  Yes, this was still wasteful (1 mother pip for 1 or 2 baby pips, whereas through communication, you could trade 1 mother pip for 5 or 6 baby pips), but at least it worked to keep a baby fed.

So what most parents did was just pick up the baby constantly, even if the baby didn't F.

Babies could (and did) just go AFK for 3 minutes.  I know that I felt that way myself whenever I was a baby.  I'd actually switch to a web browser and do something else for 3 minutes sometimes...  that sucked.

Now babies actually need to communicate to their mother, because spam feeding doesn't work at all.


All that said, I'm not at all satisfied with how this works.  However, I'm not going to just tear it out if there's not another system to replace it.  Another system which makes "going AFK for 3 minutes as a baby" untenable.


One idea that has come up is some kind of early childhood teaching system.  We've discussed the mother being able to help you "fill" extra tool slots or something by demonstrating things to you when you're a baby.  But the problem there is that a mother will just "go through the motions" every life, spamming demos of a bunch of tools.  It's hard to put my finger on it.... but there's something that doesn't feel right about that.  It's low-skill or something.... like, how could you get better at it?  Just spam more tool demos?

A new twist that I just thought of:   maybe as a baby, you "crave" certain tools, one at a time, which are your natural tendencies or something.  If you can get your mother to demo that tool for you, you learn it.  Of course, you have very limited bandwidth to talk to her, so how do you quickly tell her which tool you crave?  I dunno... this sounds like it would be a pain.  But at least it would involve some mother-baby interaction.

That's what I'm looking for...
