### ISSUE TITLE
Some foods don't satisfy cravings

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#840]
I played some games with the new update and it seems like some foods don't satisfy cravings. I've only experienced it with one food thus far (snipped pickling cucumber), but I've heard that more foods are affected by this bug. From what I've heard the issue is with foods that are grouped (like bottle, pouch and bowl of milk).

**Comment by Tarr-OHOL** [comment]
Yeah pretty sure the issue is with the grouped foods.

For example: Gooseberry can be sated with a regular gooseberry or bowl of gooseberries.
Issue is the inverse is impossible. Can't sate the bowl of gooseberries craving with either a regular or bowl of gooseberries. 

This issue extends to anything that has multiple variations (bowl of milk vs bottle vs pouch)

**Comment by jasonrohrer** [comment]
This was fixed here:

https://github.com/jasonrohrer/OneLife/issues/641

**Comment by sigmen4020** [comment]
Nice. Didn't see that issue when I made this one. I'll be closing it then.
