### ISSUE TITLE
Psilocybe Mushroom needs one hour to grow, so craving in early families can not be fulfilled by farming them

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLifeData7#842]
Possible solution:  After removing the worms it could directly go to the state with a mushroom.

alternative:

reduce growing time

**Comment by TwistedHBG** [comment]
Another alternative fix - add 2-3 extra worms to the soil pit. This will increase the recipe depth of the mushroom, making it not possible for eves to crave them any more, while at the same time being a nice QoL change for fishing.

**Comment by jasonrohrer** [comment]
This is fine as-is.

Sometimes an Eve gets stuck, unable to satisfy a craving.  Then a few generations later, everyone trips.

Cravings are above-and-beyond, and there are many examples where they "break" for a while.  That's okay, because it adds texture to the game (we've been waiting for X forever, and now we finally have a chance to get it).
