### ISSUE TITLE
Tarry spot tap-out mechanic is outdated

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLifeData7#844]
Tarry spot tapout was added during a time where ressource limitations were prevalent, namely in the rift times. This mechanic was first introduced during the rift to limit every family's access to oil, when everyone had access to a rig. Since only one race is able to gain access to tarry spots now, it doesn't make sense to limit kerosene surrounding them. The main point here is that tarry tapout was relevant when multiple families had access to oil, but now that only one race has access to it the only thing the mechanic accomplishes is limit the amount of kerosene gingers can get in close proximity, therefore further limiting the already rare tarry spots within a reasonable distance. 

Summed up; tarry spot tapout used to affect everyones access to oil, but now that oil is race restricted it only affects gingers, which are the only kerosene suppliers.

**Comment by sigmen4020** [comment]
Here's a quick example to showcase the problem:

Before with tapout a family of any race might have access to 2 tarry spots close by where one gets tapped out. Let's say there's one family of every race then the server would have easy access to 4 rigs.

Today there's the same theoretical situation; 4 families have 2 tarry spots close by with one being so close that it would tap-out. This doesn't affect 3 of the families since they can't access them anyway. So therefore it affects gingers access to oil. Now suddenly we're down to just 1 rig to supply the entire server.

I hope the problem can be seen here.

**Comment by TwistedHBG** [comment]
+1, Arctic Eves settling in a good location with more oil should be rewarded, similar to how settling near multiple iron mines is rewarded.

**Comment by jasonrohrer** [comment]
Well, the point of tap-out is to cause oil production to get harder and harder over time, because the oil wells will get farther and farther away.  Maps and way stones become necessary to preserve institutional memory across generations.  This is supposed to be true for whoever has oil, even if it's just one (ginger) family that has it.  It should get harder and harder for them to keep producing oil.

This would happen eventually without tap-out, but it would happen too slowly.

Surviving 133 generations in this game should be an absolute miracle.  This happened within the past week.  Of the four families that lives 99 or more generations within the past week, only one of them was Ginger.
