### ISSUE TITLE
Mosquitoes and other wildlife in wrong biome

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLifeData7#86]
I've seen a lot of different wildlife in the wrong biome, some biomes are supposed to be safe (at least for now) with the main concern being food because of cold but with mosquitoes in greenland or prairies it doesnt really make sense to die of a snake bite in a green area or even less in a thundra

Isn't it possible to check at each movement or something like that if it is in the right biome and if not kill/despawn the animal?

**Comment by jasonrohrer** [comment]
This is intentional.

There is a "blending" that happens at biome boundaries for object placement.  Thus, you will sometimes see a cactus at the edge of a swamp, if the swamp is near a desert.  The same is true for animals.

They always stay in their spawning biome, though.  So... arctic snakes always stay in the snow.
