### ISSUE TITLE
Engine scraping should be Elder only, require 2 people, and hungry work. It's too easy as it is.

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLifeData7#866]
It's WAY too easy as is right now. It's insane how someone can break something so important and hard to make by themselves. While stuff like property fences need elder approval. 

This needs to be relooked at.

**Comment by Arcurus** [comment]
maybe if you could place a kind of lock on the engine, which would behave like a property gate and allows interaction only from the owner(s).

**Comment by jasonrohrer** [comment]
The idea here is that an engine is very valuable and fragile, and you have to protect it.

The reason property fences take time and elder approval to remove is that they are the fundamental atom that lets you protect other things.

Walls are hungry work to destroy because it's unrealistic to chop-chop-chop and destroy a whole house in a few seconds.  But hungry work wouldn't help with the engine, because it's not like people are destroying ten engines in a row very quickly.

**Comment by squishysquid** [comment]
i have sat in nursery as a baby, and watched 4 get scrapped around me before. they do when they can...
