### ISSUE TITLE
Stacking inconsistency

### ISSUE THREAD

**Issue by Wizadroid** [jasonrohrer/OneLifeData7#878]
Since most other foods can stack, it feels like the raw and cooked variants of rabbit, mouflon and goose, as well as just the raw pork should be able to as well. As getting a lot of these things early can lead to quite the cluttered kitchen if slot boxes are not yet available.

**Comment by jasonrohrer** [comment]
Eh... thinking about this more, it seems like meats don't stack, generally.  The only cooked foods that stack must be stacked on plates.

All these primitive foods do go in baskets.  The fact that you can just set them on the bare ground at all is actually a little bit weird, and piling them up on the ground would be even weirder.

There aren't other cooked foods that can go on the ground without getting ruined.

These are primitive foods, which is why they have this special exception.... but piling them up feels to me like it would cross the line.  No one does that in real life.  While people DO pile pumpkins, tomatoes, etc.
