### ISSUE TITLE
Twins being unable to curse doesn't make sense anymore

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLifeData7#899]
With the new curse system having twins be unable to curse is beyond silly. This system was implemented in the Rift and back then it was good and made sense because we were so close together. Nowadays distance doesn't matter and curses are only really impactful to yourself. 

I have a lot of friends in the community and I am almost always a twin. It feels like I'm being punished for having friends. We're better off being born separately and coming together, and it's just fucked up. We should be allowed to curse people again.

That being said I am completely okay with not being able to join posse's.

**Comment by Arcurus** [comment]
yes, if friends want to make mess, they can simply travel from another village. No use to limit curses or posse on twins.

**Comment by Tarr-OHOL** [comment]
> yes, if friends want to make mess, they can simply travel from another village. No use to limit curses or posse on twins.

It's actually about the ability twins+ had to severely limit the section someone could spawn into the rift. Twins basically eliminated 200 tiles around themselves in a 250x250 box which then got even stricter as when the rift got to about two families you only had 1-2 towns to spawn in. 

Mechanic is definitely dated and balanced around a previous mechanic which has been since removed. +1 to allowing twins/groups to being allowed to curse again.
