### ISSUE TITLE
Horse Carts and delivery Trucks are over powered

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLifeData7#911]
Possible Solution:
Reduce speed of horses with carts from 200% to 150% (riding horse can stay same). Also reduce speed and space for trucks, maybe increase fuel use.

**Comment by IIRC-IDK** [comment]
Personally I disagree. Especially in regards to horses.

If you compare the amount of work that goes into building a truck vs a horse the space and speed makes sense. Horses run away, possibly the most annoying mechanic in the game. You could double their speed and space and they would still be annoying to use.

Going back to the current truck status. They give opening to further late game content. Content that might require a much higher oil demand. Doing oil still takes 6 trips to do with a truck. Transporting resources over long distances can take up to 10 min per trip even with the truck. Good luck transporting oil to all the fams in a life without that speed and space. Trucks are pretty well balanced as they stand, especially if higher demand content is added.

**Comment by miskas9** [comment]
Horses are hard to acquire. You always have to walk by foot to get a new one no matter what your tech level is. 
They also go missing very easily. 
If jason doesn't change those two problematic aspects of horses I cant understand why to reduce their utility.
Finally , overpowered compared to what exactly?

**Comment by TwistedHBG** [comment]
They're not overpowered

**Comment by DougLefelhocz** [comment]
Reaching other families is often not all that much fun without a horsecart or truck... except *maybe* on arc restart when families are still close.  Walking 1.7k or 2k on foot in two directions isn't something all that appealing, especially without a road and sometimes there is no road available or known about, since probably most of that life is spent preparing for the trip and then traveling.

On the contrary to this post, all families should have easier access to draft animals of some kind for travel purposes, or instantaneous teleporters between villages.

**Comment by jasonrohrer** [comment]
Seems like this is at least debatable.  Will leave it alone for now.
