### ISSUE TITLE
Players that abuse "/die" bring doom to developing families too easily

### ISSUE THREAD

**Issue by J-Ordoniez** [jasonrohrer/OneLifeData7#913]
Many people use /die to reborn back their last family. and that makes you, trying to survive to spend your precious "hungry" squares in someone that doesnt add up your family. 

I think that 48 lives is too much nowadays, and lowering it down, will make those players to think twice to /die several times

**Comment by DougLefelhocz** [comment]
Players also use /die to get born as a certain race (such as using /die to work on an oil rig or to get specialty based resources to another family), or perhaps because they use to /die to become an Eve and have started playing again not understanding that such is no longer possible.  Or to join a player who streams.  /die could also get used to deliberately tank one's genetic score if one wanted to play the game with as few pips late in life as possible.  /die could also get used to deliberately avoid inheriting leadership if people don't understand how to give up leadership.  /die could also get used, because players don't like their mother.  There likely exist more reasons why players use /die.

Note that 48 lives happened right after the September sale.  A small number of life tokens with maximum server population asks for trouble.  And small numbers of life tokens (from new players perspective) is the norm for any new players or if server(s) were filled with players.

Life tokens only known effect has been to lock players out of playing that have trouble surviving in the first place as McTravDad did while streaming on Twitch last year.  Low life tokens likely does not and _never has_ scaled well with sales or promotions, since it locks out new players who die a lot even without using /die.  

A choice screen is likely necessary to resolve the underlying issues here.  I used /die several times last night, trying to become a child of an Eve who streamed.  Neither I, nor the streamer understood that she wasn't fertile at the time.  A family selection screen could prevent such a situation from occurring, assuming, of course, that only fertile families were listed on such a screen or failure conditions were made clear if one selected a family that wasn't fertile.

**Comment by J-Ordoniez** [comment]
I know what people uses /die for, but what i'm blamming is the selfinesh in that action, and the dooming you are doing to the new family you are borning into. Many times, me as female, i've had a row of 6, 7 children slashdiying that make me mad, cause i want to care them, and they dont care to be cared.

Just saying that they make me waste my time, interrupt my actions and leech my hungry bar...

Just i find too selfish slashdying nowadays and, in my opinion, should be balanced.

**Comment by DougLefelhocz** [comment]
If life tokens were made to solve the /die issue, why remove a life token for all forms of death under a certain time?  Why not just drop life tokens *only* if the cause of death is 'sudden infant death' (clearly tracked by the game code since it's on the family trees), and limit life tokens to a small number?  That would be fewer calculations also.

**Comment by cordy-123** [comment]
you could just use the already in place mechanic of using "curse my baby" 

- which i do not recommend but the mechanic IS there for you to use.

**Comment by Tarr-OHOL** [comment]
Thread should be closed. While I think there’s too many life tokens the other times life tokens were low people straight up got locked out of playing
