### ISSUE TITLE
Hammering Key Back to Blank Too Easy (Should Have To Reforge)

### ISSUE THREAD

**Issue by Forman9** [jasonrohrer/OneLifeData7#925]
With a hammer and a file you can easily pass through ten consecutive locked doors A-J in a few minutes by filing each letter, hammering back to blank, and repeating.

If a key and lock had to be scrapped and re made (rather than hammered back to blank) keys would be more useful.  It's still possible to get through anything but takes more time and effort.

**Comment by cordy-123** [comment]
it's not that hard to make a new key and lock anyway.

**Comment by Tarr-OHOL** [comment]
This was changed from requiring both pieces to one to prevent steel griefing. You could turn two steel to one by repeating this process.

thread should be closed.

**Comment by skps2010** [comment]
I Think this should be implemented.
However, to prevent lock griefing, a lock should take some time before it is proper installed on a door. Before that, the lock can be taken away.

**Comment by jasonrohrer** [comment]
Yeah, this is interesting.  Lock security is supposed to be somewhat minimal, just like real life (anyone who knows how to make keys can easily bypass any ordinary residential lock in the US, though there are many more combinations than just 10...  There are 9 pin lengths on a standard residential lock, and most locks have 5 or 6 pins, so in the worst case, that's something like 60,000 unique key combinations.

The current engine can't do that without a huge blow-up in the generated object space, though.

Slowing the process down does make quite a bit of sense.

In fact, once you "set" a lock to one of A-J, it should be pretty permanent.  You should be able to cycle through them when creating them easily.... but after you pull the key out, that should be it for that key, unless completely re-made from scratch.

**Comment by jasonrohrer** [comment]
Yeah, this fix was pretty straight-forward.  The hammer can no longer be used to reset a lock/key pair back to blank.  You have to separate them and scrap them, and then re-make them.

You can still cycle through all the key possibilities easily when making your lock (file file file to get from A through J), but once you install it somewhere, it's status is permanent until scrapped.

You can still duplicate keys and locks, etc, as-needed, given either a key or a free lock.

But you can't turn either key or lock back into a blank without scrapping it.

**Comment by teliot** [comment]
I fear this will make it to hard to clear the very common boxed well grief.
![Screenshot 2023-08-09 130838](https://github.com/jasonrohrer/OneLifeData7/assets/6187302/5903b396-c3cf-4555-9d58-085f300ccc04)

**Comment by Tarr-OHOL** [comment]
As someone who had to deal with the well blocking before this is a TERRIBLE change. When trolls lock stuff up like this they then spend time running around smashing kilns and trying to steal stuff on horses to prevent you from unlocking it (because you have to file stuff on the ground. 

If the change only effected signs it would be fine because rarely something offensive pops up because letter working is a bunch of work so people don't normally mess with locked signs. 

Locked chests are always a troll because no one actually uses them for anything but what the picture shows - being a difficult to remove blocking tile. 

Locked doors are also a troll but has mostly stopped occurring because people now put 4+ doors on buildings to prevent that sort of trolling (plus you can pickax a wall easily now to release people.)

This complaint originally comes from a time when people were doing apocalypse attempts using unbreakable walls and then using a gauntlet of locked doors to try to slow down apocalypse attempts (which failed because lockpicking was easy to do).

If this is going to stay as a "fix" I think there should be a transition to either destroy the chest (removing the blocking) or a means to dismantle it and leave the used lock on the ground. This is an incredibly easy grief to set up and an incredibly annoying grief to deal with.

**Comment by Forman9** [comment]
At the time when I wrote this, I was using locked sheds to store kerosine caches, trucks and airplanes because the spawn was broken and the distance was like 30k between families.

Those caches and machines were necessary to keep families alive because trade was basically impossible -- but people kept breaking in.

At one point, I literally made an entire labyrinth of like 10 consecutive locked doors with the ground blocked by waystones so you had to walk the door all the way out before attempting the next door.

It was still broken through lol

At this point, locks are not particularly useful because stone walls are now breakable.
Although the chests might be worth it, I suppose.

**Comment by Tarr-OHOL** [comment]
Of course people are going to be breaking into your areas if you're locking precious resources up. This is an issue with having wondible's map more than locks and and walls existing because as long as people can see resources on the map being hoarded they're going to come and take it back (since you locking things up hurts others.) which is a topic for a different time. 

This was an awful change that enables an annoying type of griefing because no one needs to lock doors since property gates exist, signs don't matter because they're just roleplay fluff, and chests only hold four items even when locked. Someone on a horse can lock a low level town out of their water source for 8 boards and four ropes until an adze is made or produce a nightmare scenario by adding locks to the chests. 

This isn't even just doomsaying as this grief has been done before in game and is even posted directly in this issue. 

Locked doors are useless except for griefing as a property fence serves the same purpose without preventing such as surprise room locking.

Locked signs are useless because they're a fun item in game and only trolls are going to unlock a fun sign.

And of course chests are useless because people use rail carts for storage instead. Definitely should not be enabling ways like this to grief into the game.
