### ISSUE TITLE
Tools slots turn on when Apocalypse wipes server.

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLifeData7#930]
Notification of tool slots being turned on occurs after a player done server wipe. I believe this only effects survivors of the wipe as no other reports have come in on the issue.

**Comment by DougLefelhocz** [comment]
There were two streamers BlahWizard and BabyKatiez who survived the apocalypse I saw who both had tool slots activated after the apocalypse.  It doesn't apply to all descendants, at the very least, as I and trekkiea played in the same family as BabyKatiez and neither of us had tool slots.

Tux/kundarsa suspected that it had something to do with tool slots being a settings file (or it was something else being a settings file).

**Comment by cordy-123** [comment]
yes, it only affects the people who were ALIVE during apoc.

your kids don't inherit it.

since you just lived through an apoc and everything is reverted to nature, you are not gonna be able to use up the amount of tools slots you are given anyway.

but yes, it is confusing for the players who have never heard of / seen the tool slot mechanic.

"_What is that " + " sign above their head?_"

**Comment by Tarr-OHOL** [comment]
Pretty sure Jason fixed this and didn’t close thread.
