### ISSUE TITLE
Movement blocking objects can be built on Stone Road

### ISSUE THREAD

**Issue by anlongyi** [jasonrohrer/OneLifeData7#99]
Objects which block movement such as Wooden Box can be built directly on a Stone Road, making the route awkward and halting to run along. 

This is not a problem for wooden or stone floors, which usually have good reason to build structures upon (such as bakery storage). But as the main purpose of Stone Road is to increase travel speed, there is (edit: probably) no reason to allow structures that block movement except as another problem to clean up.

**Comment by jasonrohrer** [comment]
Hmm... what about doors?  In other words, gates on the road?

This is intentional.  People can build whatever they want wherever they want.

There are some things that don't make physical sense (like planting potatoes on a stone floor), but beyond that, I'm not going to guess what people are going to try to do.
